let cccaggBTCsubs = require("./BTC-CCCAGG-subs");
let cccaggETHsubs = require("./ETH-CCCAGG-subs");
let cccaggBNBsubs = require("./BNB-CCCAGG-subs");
let currentCoinsubs = require("./CURRENT-COIN-USD-subs");
let tradeCoinsubs = require("./TRADE-COIN-USD-subs");
let tempArr = [];
tempArr = cccaggBTCsubs.concat(cccaggETHsubs);
tempArr = tempArr.concat(currentCoinsubs);
tempArr = tempArr.concat(tradeCoinsubs);
tempArr = tempArr.concat(cccaggBNBsubs);
console.log(tempArr);
module.exports = tempArr;
