language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=5000
install:
  - npm install
notifications:
  slack: webexchange:2A0pvs6b8GEwERGSKU50Uj2K
script:
  - nohup npm run start &
  - sleep 3
  - npm test
