module.exports = {42 : "42 Coin",
300 : "300 token",
365 : "365Coin",
404 : "404Coin",
611 : "SixEleven",
808 : "808",
888 : "Octocoin",
1337 : "1337",
2015 : "2015 coin",
BTC : "Bitcoin",
ETH : "Ethereum", 
LTC : "Litecoin",
DASH : "Dash",
XMR : "Monero",
NXT : "Nxt",
ETC : "Ethereum Classic",
DOGE : "Dogecoin",
ZEC : "ZCash",
BTS : "Bitshares",
DGB : "DigiByte",
BTCD : "BitcoinDark",
PPC : "PeerCoin",
CRAIG : "CraigsCoin",
XBS : "Bitstake",
XPY : "PayCoin",
PRC : "ProsperCoin",        
YBC : "YbCoin", 
DANK : "DarkKush",
GIVE : "GiveCoin",
KOBO : "KoboCoin",
DT : "DarkToken",
CETI : "CETUS Coin",
SUP : "Supcoin",
XPD : "PetroDollar",
GEO : "GeoCoin",
CHASH : "CleverHash",
SPR : "Spreadcoin",
NXTI : "NXTI",
WOLF : "Insanity Coin",
XDP : "DogeParty",
AC : "Asia Coin",
ACOIN : "ACoin",
AERO : "Aero Coin",
ALF : "AlphaCoin",
AGS : "Aegis",
AMC : "AmericanCoin",
ALN : "AlienCoin",
APEX : "ApexCoin",
ARCH : "ArchCoin",
ARG : "Argentum",
ARI : "AriCoin",
AUR : "Aurora Coin",
AXR : "AXRON",
BCX : "BattleCoin",
"BEN*" : "Benjamins",
BET : "BetaCoin",
BITB : "BitBean",
BLU : "BlueCoin",
BLK : "BlackCoin",
BOST : "BoostCoin",
BQC : "BQCoin",
XMY : "MyriadCoin",
MOON : "MoonCoin",
ZET : "ZetaCoin",
SXC : "SexCoin",
QTL : "Quatloo",
ENRG : "EnergyCoin",
QRK : "QuarkCoin",
RIC : "Riecoin",
DGC : "DigiCoin",
LIMX : "LimeCoinX",
BTB : "BitBar",
CAIX : "CAIx",
BTE : "ByteCoin",
"BTG*" : "BitGem",
BUK : "CryptoBuk",
CACH : "Cachecoin",
CANN : "CannabisCoin",
CAP : "BottleCaps",
CASH : "CashCoin",
CAT1 : "Catcoin",
CBX : "CryptoBullion",
CCN : "CannaCoin",
CIN : "CinderCoin",
CINNI : "CINNICOIN",
CXC : "CheckCoin",
CLAM : "CLAMS",
CLOAK : "CloakCoin",
CLR : "CopperLark",
CMC : "CosmosCoin",
CNC : "ChinaCoin",
CNL : "ConcealCoin",
COMM : "Community Coin",
COOL : "CoolCoin",
CRACK : "CrackCoin",
"CRC*" : "CraftCoin",
CRYPT : "CryptCoin",
DEM : "eMark",
DMD : "Diamond",
XVG : "Verge",
DRKC : "DarkCash",
DSB : "DarkShibe",
DVC : "DevCoin",
EAC : "EarthCoin",
EFL : "E-Gulden",
ELC : "Elacoin",
EMC2 : "Einsteinium",
EMD : "Emerald",
EXCL : "Exclusive Coin",
EXE : "ExeCoin",
EZC : "EZCoin",
FLAP : "Flappy Coin",
FC2 : "Fuel2Coin",
FFC : "FireflyCoin",
FIBRE : "FIBRE",
FRC : "FireRoosterCoin",
FLT : "FlutterCoin",
FRK : "Franko",
FRAC : "FractalCoin",
FST : "FastCoin",
FTC : "FeatherCoin",
GDC : "GrandCoin",
GLC : "GlobalCoin",
GLD : "GoldCoin",
GLX : "GalaxyCoin",
GLYPH : "GlyphCoin",
GML : "GameLeagueCoin",
GUE : "GuerillaCoin",
HAL : "Halcyon",
HBN : "HoboNickels",
HUC : "HunterCoin",
HVC : "HeavyCoin",
HYP : "Hyperstake",
ICB : "IceBergCoin",
IFC : "Infinite Coin",
IOC : "IOCoin",
IXC : "IXcoin",
JBS : "JumBucks Coin",
JKC : "JunkCoin",
JUDGE : "JudgeCoin",
KDC : "Klondike Coin",
"KEY*" : "KeyCoin",
KGC : "KrugerCoin",
"LAB*" : "CoinWorksCoin",
"LGD*" : "Legendary Coin",
LK7 : "Lucky7Coin",
LKY : "LuckyCoin",
LSD : "LightSpeedCoin",
LTB : "Litebar ",
LTCD : "LitecoinDark",
LTCX : "LitecoinX",
LXC : "LibrexCoin",
LYC : "LycanCoin",
MAX : "MaxCoin",
NICE : "NiceCoin",
SMF : "SmurfCoin",
CWXT : "CryptoWorldXToken",
TECH : "TechCoin",
CIR : "CircuitCoin",
LEPEN : "LePenCoin",
ROUND : "RoundCoin",
MAR : "MarijuanaCoin",
MARX : "MarxCoin",
TAT : "Tatiana Coin",
HAZE : "HazeCoin",
PRX : "Printerium",
NRC : "Neurocoin",
PAC : "PacCoin",
IMPCH : "Impeach",
ERR : "ErrorCoin",
TIC : "TrueInvestmentCoin",
NUKE : "NukeCoin",
EOC : "EveryonesCoin",
SFC : "Solarflarecoin",
JANE : "JaneCoin",
PARA : "ParanoiaCoin",
MM : "MasterMint",
NDOGE : "NinjaDoge",
ZBC : "Zilbercoin",
FRST : "FirstCoin",
PAY : "TenX",
ORO : "OroCoin",
ALEX : "Alexandrite",
TBCX : "TrashBurn",
MCAR : "MasterCar",
THS : "TechShares",
ACES : "AcesCoin",
UAEC : "United Arab Emirates Coin",
EA : "EagleCoin",
PIE : "Persistent Information Exchange",
CREA : "CreativeChain",
WISC : "WisdomCoin",
BVC : "BeaverCoin",
FIND : "FindCoin",
MLITE : "MeLite",
STALIN : "StalinCoin",
TSE : "TattooCoin",
VLTC : "VaultCoin",
BIOB : "BioBar",
PASL : "Pascal Lite",
ZER : "Zero",
CHAT : "ChatCoin",
CDN : "Canada eCoin",
TPAY : "TrollPlay",
NETKO : "Netko",
ZOI : "Zoin",
HONEY : "Honey",
MXT : "MartexCoin",
MUSIC : "Musicoin",
DTB : "Databits",
VEG : "BitVegan",
MBIT : "Mbitbooks",
VOLT : "BitVolt",
"B@" : "BankCoin",
BEST : "BestChain",
CHC : "ChainCoin",
ZENI : "Zennies",
PLANET : "PlanetCoin",
DUCK : "DuckDuckCoin",
BNX : "BnrtxCoin",
BSTK : "BattleStake",
RNS : "RenosCoin",
DBIX : "DubaiCoin",
AMIS : "AMIS",
KAYI : "Kayı",
XVP : "VirtacoinPlus",
BOAT : "Doubloon",
TAJ : "TajCoin",
IMX : "Impact",
CJC : "CryptoJournal",
AMY : "Amygws",
QBT : "Cubits",
"SRC*" : "StarCredits",
EB3 : "EB3coin",
XVE : "The Vegan Initiative",
FAZZ : "FazzCoin",
APT : "Aptcoin",
BLAZR : "BlazerCoin",
ARPA : "ArpaCoin",
"BNB*" : "Boats and Bitches",
UNI : "Universe",
ECO : "ECOcoin",
XLR : "Solaris",
DARK : "Dark",
DON : "DonationCoin",
MER : "Mercury",
WGO : "WavesGO",
ATMOS : "Atmos",
INPAY : "InPay",
ETT : "EncryptoTel",
"WBTC*" : "wBTC",
VISIO : "Visio",
HPC : "HappyCoin",
GOT : "Giotto Coin",
CXT : "Coinonat",
EMPC : "EmporiumCoin",
LGD : "Legends Cryptocurrency",
BUCKS : "SwagBucks",
XBY : "XtraBYtes",
GUP : "Guppy",
MCRN : "MacronCoin",
RAIN : "Condensate",
WSX : "WeAreSatoshi",
IEC : "IvugeoEvolutionCoin",
IMS : "Independent Money System",
ARGUS : "ArgusCoin",
CNT : "Centurion",
LMC : "LomoCoin",
BTCS : "Bitcoin Scrypt",
PROC : "ProCurrency",
XGR : "GoldReserve",
"WRC*" : "WarCoin",
BENJI : "BenjiRolls",
DUO : "ParallelCoin",
RBX : "RiptoBuX",
GRW : "GrowthCoin",
APX : "Apx",
MILO : "MiloCoin",
OLV : "OldV",
ILC : "ILCoin",
MRT : "MinersReward",
IOU : "IOU1",
PZM : "Prizm",
PHR : "Phreak",
PUPA : "PupaCoin",
RICE : "RiceCoin",
XCT : "C-Bits",
DEA : "Degas Coin",
RED : "Redcoin",
ZSE : "ZSEcoin",
CTIC : "Coinmatic",
TAP : "TappingCoin",
BITOK : "BitOKX",
PBT : "Primalbase",
MUU : "MilkCoin",
INF8 : "Infinium-8",
HTML5 : "HTML5 Coin",
MNE : "Minereum",
DICE : "Etheroll",
"SUB*" : "Subscriptio",
USC : "Ultimate Secure Cash",
DUX : "DuxCoin",
XPS : "PoisonIvyCoin",
EQT : "EquiTrader",
INSN : "Insane Coin",
"MAT*" : "Manet Coin",
F16 : "F16Coin",
HAMS : "HamsterCoin",
QTUM : "QTUM",
NEF : "NefariousCoin",
ZEN : "ZenCash",
BOS : "BOScoin",
QWARK : "Qwark",
IOT : "IOTA",
ADL : "Adelphoi",
"ECC*" : "E-CurrencyCoin",
ZRC : "ZrCoin",
LKK : "Lykke",
ESP : "Espers",
"MAD*" : "SatoshiMadness",
DYN : "Dynamic",
SEQ : "Sequence",
MCAP : "MCAP",
SKY : "Skycoin",
CFI : "Cofound.it",
IXT : "iXledger",
STA : "Starta",
EFYT : "Ergo",
XTZ : "Tezos",
QAU : "Quantum",
ECOB : "EcoBit",
USDT : "Tether",
NANO : "Nano",
AHT : "Ahoolee",
ATB : "ATB coin",
CHAN : "ChanCoin",
CMP : "Compcoin",
HRB : "Harbour DAO",
"8BT" : "8 Circuit Studios",
ACT : "ACT",
SUR : "Suretly",
PING : "CryptoPing",
MIV : "MakeItViral",
WGR : "Wagerr",
XEL : "Elastic",
NVST : "NVO",
FUNC : "FunCoin",
PQT : "PAquarium",
SNC : "SunContract",
STAR : "Starbase",
COR : "Corion",
OROC : "Orocrypt",
OAX : "OpenANX",
MBI : "Monster Byte Inc",
DDF : "Digital Developers Fund",
DIM : "DIMCOIN",
GGS : "Gilgam",
DNA : "EncrypGen",
FYN : "FundYourselfNow",
FND : "FundRequest",
DCY : "Dinastycoin",
CFT : "CryptoForecast",
DNR : "Denarius",
DP : "DigitalPrice",
VUC : "Virta Unique Coin",
BTPL : "Bitcoin Planet",
UNIFY : "Unify",
IPC : "ImperialCoin",
BRIT : "BritCoin",
AMMO : "Ammo Rewards",
SOCC : "SocialCoin",
MASS : "Mass.Cloud",
LA : "LATOKEN",
IML : "IMMLA",
XUC : "Exchange Union",
STU : "BitJob",
GUNS : "GeoFunders",
SYC : "SynchroCoin",
"AHT*" : "Bowhead Health",
TRIBE : "TribeToken",
NPX : "Napoleon X",
SCORE : "Scorecoin",
OTX : "Octanox",
EQB : "Equibit",
CVCOIN : "Crypviser",
ARC : "ArcticCoin",
BOG : "Bogcoin",
ADT : "AdToken",
UET : "Useless Ethereum Token",
PART : "Particl",
AGRS : "Agoras Token",
SAND : "BeachCoin",
"XAI*" : "AICoin",
DMT : "DMarket",
DAS : "DAS",
XCJ : "CoinJob",
RKC : "Royal Kingdom Coin",
NLC2 : "NoLimitCoin",
LINDA : "Linda",
SPN : "Spoon",
KING : "King93",
ANCP : "Anacrypt",
RCC : "Reality Clash",
ROOTS : "RootProject",
SNK : "Sosnovkino",
CABS : "CryptoABS",
ZNT : "OpenZen",
BITSD : "Bits Digit",
XLC : "LeviarCoin",
SKIN : "Skincoin",
HIRE : "HireMatch",
"BBT*" : "BrickBlock",
DFBT : "DentalFix",
EQ : "EQUI",
WLK : "Wolk",
VIB : "Viberate",
ONION : "DeepOnion",
BTX : "Bitcore",
ICE : "iDice",
XID : "Sphre AIR",
GCN : "gCn Coin",
"ATOM*" : "Cosmos",
ICOO : "ICO OpenLedger",
TME : "Timereum",
SIGT : "Signatum",
ONX : "Onix",
COE : "CoEval",
ARENA : "Arena",
WINK : "Wink",
CRM : "Cream",
BCH : "Bitcoin Cash",
DGPT : "DigiPulse",
MOBI : "Mobius",
SDAO : "Solar DAO",
CORE : "Core Group Asset",
KEN : "Kencoin",
QVT : "Qvolta",
AUT : "Autoria",
CTT : "CodeTract",
GRWI : "Growers International",
MNY : "Monkey",
MTH : "Monetha",
CCC : "CCCoin",
UMC : "Umbrella Coin",
BMXT : "Bitmxittz",
GAS : "Gas",
FIL : "FileCoin",
OCL : "Oceanlab",
BNC : "Benjacoin",
TOM : "Tomahawkcoin",
XAS : "Asch",
SMNX : "SMNX",
DLT : "Agrello Delta",
MRV : "Macroverse",
MBRS : "Embers",
MET : "Memessenger",
NEBL : "Neblio",
PGL : "Prospectors",
XMCC : "Monoeci",
AUN : "Authoreon",
"CASH*" : "Cash Poker Pro",
CMPCO : "CampusCoin",
DTCT : "DetectorToken",
WNET : "Wavesnode.net",
THNX : "ThankYou",
WORM : "HealthyWorm",
VNT : "Veredictum",
SIFT : "Smart Investment Fund Token",
IGNIS : "Ignis",
IWT : "IwToken",
JDC : "JustDatingSite",
ITT : "Intelligent Trading",
LNC : "BlockLancer",
AIX : "Aigang",
XEC : "Eternal Coin",
ENTRP : "Entropy Token",
ICOS : "ICOBox",
PIX : "Lampix",
MEDI : "MediBond",
LTA : "Litra",
NIMFA : "Nimfamoney",
SCOR : "Scorista",
MLS : "CPROP",
KEX : "KexCoin",
BRO : "Bitradio",
MINEX : "Minex",
"MAG*" : "Magos",
DFT : "Draftcoin",
LAT : "Latium",
SOJ : "Sojourn Coin",
STCN : "Stakecoin",
SQP : "SqPay",
RIYA : "Etheriya",
LNK : "Ethereum.Link",
WAN : "Wanchain",
MNTP : "GoldMint",
ALTOCAR : "AltoCar",
"CFT*" : "Credo",
BLX : "Blockchain Index",
BOU : "Boulle",
OXY : "Oxycoin",
TTT : "Tap Project",
AMT : "Acumen",
GIM : "Gimli",
NYC : "NewYorkCoin",
LBTC : "LiteBitcoin",
FRAZ : "FrazCoin",
EMT : "EasyMine",
GXC : "Gx Coin",
KRONE : "Kronecoin",
SRT : "Scrypto",
AVA : "Avalon",
BT : "BuildTeam",
ACC : "AdCoin",
"AR*" : "Ar.cash",
Z2 : "Z2 Coin",
LINX : "Linx",
XCXT : "CoinonatX",
BLAS : "BlakeStar",
GOOD : "GoodCoin",
TRV : "Travel Coin",
CRTM : "Cryptum",
EON : "Exscudo",
CTX : "CarTaxi",
CNX : "Cryptonex",
DRC : "Dropcoin",
ACE : "TokenStars",
BRX : "Breakout Stake",
UCASH : "U.CASH",
WRT : "WRTcoin",
ORME : "Ormeus Coin",
DEEP : "Deep Gold",
"TMT*" : "ToTheMoon",
CCT : "Crystal Clear Token ",
WSH : "Wish Finance",
"ARNA*" : "ARNA Panacea",
ABC : "AB-Chain",
PRP : "Papyrus",
"SKR*" : "Skrilla Token",
"3DES" : "3DES",
PYN : "Paycentos",
KAPU : "Kapu",
CAPP : "Cappasity",
FC : "Facecoin",
RCN : "Ripio",
NRN : "Doc.ai Neuron",
WIZ : "Crowdwiz",
ATKN : "A-Token",
RUSTBITS : "Rustbits",
ETHD : "Ethereum Dark",
SUMO : "Sumokoin",
H2O : "Hydrominer",
TKT : "Crypto Tickets",
RHEA : "Rhea",
MTN : "TrackNetToken",
STOCKBET : "StockBet",
PLM : "Algo.Land",
SND : "Sandcoin",
XP : "Experience Points",
HSR : "Hshare",
ZNA : "Zenome",
EZM : "EZMarket",
ODN : "Obsidian",
MTK : "Moya Token",
CAS : "Cashaa",
MAT : "MiniApps",
GJC : "Global Jobcoin",
WIC : "Wi Coin",
WAND : "WandX",
ELIX : "Elixir",
EBTC : "eBitcoin",
ADA : "Cardano",
REC : "Regalcoin",
BIS : "Bismuth",
OPP : "Opporty",
ROCK : "Ice Rock Mining",
EARTH : "Earth Token",
VSX : "Vsync",
"WISH*" : "WishFinance",
FLASH : "FLASH coin",
GRFT : "Graft Blockchain",
BTCZ : "BitcoinZ",
CZC : "Crazy Coin",
GUESS : "Peerguess",
ETP : "Metaverse",
CIX : "Cryptonetix",
ERT : "Esports.com",
"BAC*" : "LakeBanker",
FLIK : "FLiK",
MBT : "Multibot",
JVY : "Javvy",
ARBI : "Arbi",
ELT : "Eloplay",
ARN : "Aeron",
ROK : "Rockchain",
XRED : "X Real Estate Development",
DAY : "Chronologic",
HXT : "HextraCoin",
"VRP*" : "Prosense.tv",
NTM : "NetM",
TZC : "TrezarCoin",
MCI : "Musiconomi",
NTO : "Fujinto",
ATCC : "ATC Coin",
KOLION : "Kolion",
WILD : "Wild Crypto",
ELTC2 : "eLTC",
ILCT : "ILCoin Token",
RYZ : "Anryze",
"GXC*" : "GenXCoin",
ELM : "Elements",
TER : "TerraNovaCoin",
XCS : "CybCSec Coin",
BQ : "Bitqy",
CAV : "Caviar",
CLOUT : "Clout",
"PTC*" : "Propthereum",
EVR : "Everus",
TOA : "TOA Coin",
MNZ : "Monaize",
VIVO : "VIVO Coin",
RPX : "Red Pulse",
AURS : "Aureus",
CAG : "Change",
ECHT : "e-Chat",
INXT : "Internxt",
ATS : "Authorship",
RGC : "RG Coin",
EBET : "EthBet",
"BM*" : "Bitcomo",
WHL : "WhaleCoin",
BTG : "Bitcoin Gold",
ETG : "Ethereum Gold",
WOMEN : "WomenCoin",
MAY : "Theresa May Coin",
RNDR : "Render Token",
EDDIE : "Eddie coin",
"SCT*" : "Soma",
NAMO : "NamoCoin",
KCS : "Kucoin",
FLLW : "Follow Coin",
WYR : "Wyrify",
VZT : "Vezt",
INDI : "IndiCoin",
LUX : "LUXCoin",
BAR : "TBIS token",
PIRL : "Pirl",
ECASH : "Ethereum Cash",
ODMC : "ODMCoin",
"CABS*" : "CyberTrust",
BRAT : "BROTHER",
DTR : "Dynamic Trading Rights",
TKR : "CryptoInsight",
ELITE : "EthereumLite",
XIOS : "Xios",
DOVU : "DOVU",
ETN : "Electroneum",
REA : "Realisto",
AVE : "Avesta",
XNN : "Xenon",
BTDX : "Bitcloud 2.0",
"LOAN*" : "Lendoit",
"DTT*" : "Data Trading",
ZAB : "ZABERcoin",
"MDL*" : "Modulum",
BT1 : "Bitfinex Bitcoin Future",
BT2 : "Bitcoin SegWit2X",
JCR : "Jincor",
XSB : "Extreme Sportsbook",
EBST : "eBoost",
KEK : "KekCoin",
"BHC*" : "BlackholeCoin",
ALTCOM : "AltCommunity Coin",
OST : "Simple Token",
UGC : "ugChain",
DTC : "Datacoin",
PURE : "Pure",
CLD : "Cloud",
POS : "PoSToken",
NEOG : "NEO Gold",
EXN : "ExchangeN",
TRCT : "Tracto",
BTCRED : "Bitcoin Red",
EBCH : "eBitcoinCash",
JTX : "Project J",
AXT : "AIX",
NEU : "Neumark",
RUPX : "Rupaya",
BDR : "BlueDragon",
XIN : "Infinity Economics",
DUTCH : "Dutch Coin",
"HNC*" : "Huncoin",
"MDC*" : "MadCoin",
PURA : "Pura",
INN : "Innova",
BDL : "Bitdeal",
CMS : "COMSA",
XBL : "Billionaire Token",
ZEPH : "Project Zephyr",
ATFS : "ATFS Project",
GES : "Galaxy eSolutions",
"PHR*" : "Phore",
LCASH : "LitecoinCash",
CFD : "Confido",
PLC : "PlusCoin",
SRN : "SirinLabs",
WSC : "WiserCoin",
XGOX : "Go!",
NEWB : "Newbium",
LIFE : "LIFE",
RMC : "Russian Mining Coin",
MSR : "Masari",
CJT : "ConnectJob Token",
"ESC*" : "Ethersportcoin",
BNK : "Bankera",
ELLA : "Ellaism",
BPL : "BlockPool",
DRXNE : "Droxne",
SKR : "Sakuracoin",
XPTX : "PlatinumBAR",
GVT : "Genesis Vision",
GMT : "Mercury Protocol",
"EPY*" : "Emphy",
"HOLD*" : "Interstellar Holdings",
MNX : "MinexCoin",
CRDS : "Credits",
VIU : "Viuly",
"SCR*" : "Scorum",
DBR : "Düber",
ABT : "Advanced Browsing Token",
GFT : "Giftcoin",
STAC : "STAC",
RIPT : "RiptideCoin",
BBT : "BitBoost",
GBX : "GoByte",
CSTL : "Castle",
ICC : "Insta Cash Coin",
ALQO : "Alqo",
"KNC**" : "KingN Coin",
TRIA : "Triaconta",
MAG : "Magnet",
STEX : "STEX",
TAU : "Lamden Tau",
LAB : "Labrys",
FRD : "Farad",
ECA : "Electra",
LDM : "Ludum token",
LTG : "LiteCoin Gold",
BCD : "Bitcoin Diamond",
STP : "StashPay",
AERM : "Aerium",
PLX : "PlexCoin",
ETHB : "EtherBTC",
CDX : "Commodity Ad Network",
FOOD : "FoodCoin",
VOT : "Votecoin",
SETH : "Sether",
"TIO*" : "Tio Tour Guides",
ABYSS : "The Abyss",
XSH : "SHIELD",
"BCD*" : "BitCAD",
GEA : "Goldea",
"BCO*" : "BridgeCoin",
DSR : "Desire",
ONG : "onG.social",
BTCM : "BTCMoon",
ETBT : "Ethereum Black",
ZCG : "ZCashGOLD",
MUT : "Mutual Coin",
MEOW : "Kittehcoin",
DIVX : "Divi",
CNBC : "Cash & Back Coin",
"ARC*" : " Arcade City",
XUN : "UltraNote",
RFL : "RAFL",
ELTCOIN : "ELTCOIN",
GRX : "Gold Reward Token",
NTK : "Neurotoken",
ERO : "Eroscoin",
MAN : "People",
CWV : "CryptoWave",
"ACT*" : "Achain",
NRO : "Neuro",
SEND : "Social Send",
GLT : "GlobalToken",
COAL : "BitCoal",
DAXX : "DaxxCoin",
BWK : "Bulwark",
FNTB : "FinTab",
XMRG : "Monero Gold",
BTCE : "EthereumBitcoin",
BOXY : "BoxyCoin",
UTN : "Universa",
EGAS : "ETHGAS",
DPP : "Digital Assets Power Play",
BMT : "BMChain",
BIO : "Biocoin",
MTRC : "ModulTrade",
BTCL : "BTC Lite",
PCN : "PeepCoin",
PYP : "PayPro",
RBTC : "Bitcoin Revolution",
CRED : "Verify",
SBTC : "Super Bitcoin",
KLKS : "Kalkulus",
AC3 : "AC3",
GTO : "GIFTO",
TNB : "Time New Bank",
"CHIPS*" : "CHIPS",
"LOC*" : "LockTrip",
"MNT*" : "Media Network Coin",
ITNS : "IntenseCoin",
"SMT*" : "SmartMesh",
GER : "GermanCoin",
LTCU : "LiteCoin Ultra",
EMGO : "MobileGo",
BTCA : "Bitair",
HQX : "HOQU",
ETF : "EthereumFog",
"BCX*" : "BitcoinX",
"LUX**" : "Luxmi Coin",
STAK : "Straks",
BCOIN : "BannerCoin",
"MED*" : "MediBloc",
CCOS : "CrowdCoinage",
HAT : "Hawala.Today",
VLR : "Valorem",
CWX : "Crypto-X",
DBC : "DeepBrain Chain",
"ZEN*" : "Zen Protocol",
POP : "PopularCoin",
"CRC***" : "CrowdCoin",
PNX : "PhantomX",
BAS : "BitAsean",
HBC : "HomeBlockCoin",
AMM : "MicroMoney",
DAV : "DavorCoin",
XCPO : "Copico",
GENE : "PARKGENE",
NMS : "Numus",
PHO : "Photon",
XTRA : "ExtraCredit",
HION : "Handelion",
NTWK : "Network Token",
SUCR : "Sucre",
"SMART*" : "SmartBillions",
ACCO : "Accolade",
BTH : "Bytether ",
REM : "REMME",
TOK : "TokugawaCoin",
EREAL : "eREAL",
CPN : "CompuCoin",
XFT : "Fantasy Cash",
QLC : "QLC Chain",
BTSE : "BitSerial",
OMGC : "OmiseGO Classic",
Q2C : "QubitCoin",
BLT : "Bloom Token",
TDS : "TokenDesk",
ORE : "Galactrum",
SPK : "Sparks",
GOA : "GoaCoin",
FLS : "Fuloos Coin",
WAGE : "Digiwage",
GUN : "GunCoin",
DFS : "DFSCoin",
POLIS : "PolisPay",
WELL : "Well",
FLOT : "FireLotto",
CL : "CoinLancer",
SHND : "StrongHands",
AUA : "ArubaCoin",
SAGA : "SagaCoin",
GXS : "GXChain",
TSL : "Energo",
IRL : "IrishCoin",
BOT : "Bodhi",
PMA : "PumaPay",
TROLL : "Trollcoin",
FOR : "Force Coin",
SGR : "Sugar Exchange",
JET : "Jetcoin",
MDS : "MediShares",
LCP : "Litecoin Plus",
IETH : "iEthereum",
"GCC*" : "TheGCCcoin",
INK : "Ink",
KBR : "Kubera Coin",
JINN : "Jinn",
SET : "Setcoin",
MGN : "MagnaCoin",
KZC : "KZCash",
GNR : "Gainer",
LWF : "Local World Forwarders",
BRC : "BrightCoin",
WCG : "World Crypto Gold",
HIVE : "Hive",
GX : "GameX",
ETL : "EtherLite",
DRG : "Dragon Coin",
"BRC*" : "BinaryCoin",
"SPX*" : "Sp8de",
AIDOC : "AI Doctor",
ECC : "ECC",
ET4 : "Eticket4",
LCT : "LendConnect",
VST : "Vestarin",
STN : "Steneum Coin",
SFU : "Saifu",
PCOIN : "Pioneer Coin",
"BLN*" : "Bolenum",
LUC : "Play 2 Live",
EDT : "EtherDelta",
CYDER : "Cyder Coin",
SRNT : "Serenity",
MLT : "MultiGames",
UBTC : "UnitedBitcoin",
BTO : "Bottos",
DOC : "Doc Coin",
ARCT : "ArbitrageCT",
IDH : "IndaHash",
ITZ : "Interzone",
XBP : "Black Pearl Coin",
EXRN : "EXRNchain",
BFT : "BF Token",
SGL : "Sigil",
TNC : "Trinity Network Credit",
CFTY : "Crafty",
DTA : "Data",
CV : "CarVertical",
DTX : "DataBroker DAO",
MCU : "MediChain",
OCN : "Odyssey",
PRPS : "Purpose",
DUBI : "Decentralized Universal Basic Income",
BPT : "Blockport",
SGN : "Signals Network",
TCT : "TokenClub ",
ZIL : "Zilliqa",
"QBT*" : "Qbao",
"ACC*" : "Accelerator Network",
SWFTC : "SwftCoin",
OPC : "OP Coin",
SAF : "Safinus",
SHA : "Shacoin",
PYLNT : "Pylon Network",
GRLC : "Garlicoin",
REPUX : "Repux",
JOY : "JoyToken",
"GTC*" : "Global Tour Coin",
"XCD*" : "Capdax",
BTW : "BitcoinWhite",
AXP : "aXpire",
FOTA : "Fortuna",
DDD : "Scry.info",
SPEND : "Spend",
ZPT : "Zeepin",
CROAT : "Croat",
REF : "RefToken",
LDC : "LeadCoin",
"FAIR*" : "FairGame",
VAL : "Valorbit",
BCDN : "BlockCDN ",
STK : "STK Token",
MZX : "Mosaic Network",
"CRC**" : "CryCash",
SPICE : "SPiCE Venture Capital ",
Q1S : "Quantum1Net",
XTO : "Tao",
ELA : "Elastos",
"TPAY*" : "TokenPay",
CXO : "CargoX",
WT : "WeToken",
HGS : "HashGains",
SISA : "Strategic Investments in Significant Areas",
EBIT : "eBit",
CUZ : "Cool Cousin",
HLC : "Halal-Chain",
GMR : "Gimmer",
ING : "Iungo",
LHC : "LHCoin",
BLZ : "Bluzelle",
HALAL : "Halal",
"CRAVE*" : "Crave-NG",
CHSB : "SwissBorg",
EQUI : "EQUI Token",
MCT : "1717 Masonic Commemorative Token",
HHEM : "Healthureum",
CWIS : "Crypto Wisdom Coin",
MBC : "My Big Coin",
GRO : "Gron Digital",
"MTN*" : "Medicalchain",
WBTC : "WorldBTC",
DNO : "Denaro",
eFIC : "FIC Network",
TKY : "THEKEY Token",
TRTL : "TurtleCoin",
"CARE*" : "Care Token",
DRPU : "DRP Utility",
DOR : "Dorado",
PRFT : "Proof Suite Token",
DTRC : "Datarius",
IQB : "Intelligence Quotient Benefit",
"NDC*" : "NeedleCoin",
MUN : "MUNcoin",
TIG : "Tigereum",
NYX : "NYXCOIN",
SAT : "Satisfaction Token",
CRL : "Cryptelo Coin",
ORI : "Origami",
LYM : "Lympo",
USX : "Unified Society USDEX",
LGR : "Logarithm",
BCA : "Bitcoin Atom",
B2X : "SegWit2x",
EXMR : "eXMR Monero",
UETL : "Useless Eth Token Lite",
NBR : "Niobio Cash",
RAVE : "Ravelous",
ILT : "iOlite",
SCOOBY : "Scooby coin",
CEFS : "CryptopiaFeeShares",
"MINT*" : "Mineable Token",
BUN : "BunnyCoin",
BSR : "BitSoar Coin",
SKULL : "Pirate Blocks",
TRDT : "Trident",
XBTY : "Bounty",
JC : "JesusCoin",
42 : "42 Coin",
300 : "300 token",
365 : "365Coin",
404 : "404Coin",
611 : "SixEleven",
808 : "808",
888 : "Octocoin",
1337 : "1337",
2015 : "2015 coin",
BTC : "Bitcoin",
ETH : "Ethereum",
LTC : "Litecoin",
DASH : "Dash",
XMR : "Monero",
NXT : "Nxt",
ETC : "Ethereum Classic",
DOGE : "Dogecoin",
ZEC : "ZCash",
BTS : "Bitshares",
DGB : "DigiByte",
BTCD : "BitcoinDark",
PPC : "PeerCoin",
CRAIG : "CraigsCoin",
XBS : "Bitstake",
XPY : "PayCoin",
PRC : "ProsperCoin",
YBC : "YbCoin",
DANK : "DarkKush",
GIVE : "GiveCoin",
KOBO : "KoboCoin",
DT : "DarkToken",
CETI : "CETUS Coin",
SUP : "Supcoin",
XPD : "PetroDollar",
GEO : "GeoCoin",
CHASH : "CleverHash",
SPR : "Spreadcoin",
NXTI : "NXTI",
WOLF : "Insanity Coin",
XDP : "DogeParty",
AC : "Asia Coin",
ACOIN : "ACoin",
AERO : "Aero Coin",
ALF : "AlphaCoin",
AGS : "Aegis",
AMC : "AmericanCoin",
ALN : "AlienCoin",
APEX : "ApexCoin",
ARCH : "ArchCoin",
ARG : "Argentum",
ARI : "AriCoin",
AUR : "Aurora Coin",
AXR : "AXRON",
BCX : "BattleCoin",
"BEN*" : "Benjamins",
BET : "BetaCoin",
BITB : "BitBean",
BLU : "BlueCoin",
BLK : "BlackCoin",
BOST : "BoostCoin",
BQC : "BQCoin",
XMY : "MyriadCoin",
MOON : "MoonCoin",
ZET : "ZetaCoin",
SXC : "SexCoin",
QTL : "Quatloo",
ENRG : "EnergyCoin",
QRK : "QuarkCoin",
RIC : "Riecoin",
DGC : "DigiCoin",
LIMX : "LimeCoinX",
BTB : "BitBar",
CAIX : "CAIx",
BTE : "ByteCoin",
"BTG*" : "BitGem",
BUK : "CryptoBuk",
CACH : "Cachecoin",
CANN : "CannabisCoin",
CAP : "BottleCaps",
CASH : "CashCoin",
CAT1 : "Catcoin",
CBX : "CryptoBullion",
CCN : "CannaCoin",
CIN : "CinderCoin",
CINNI : "CINNICOIN",
CXC : "CheckCoin",
CLAM : "CLAMS",
CLOAK : "CloakCoin",
CLR : "CopperLark",
CMC : "CosmosCoin",
CNC : "ChinaCoin",
CNL : "ConcealCoin",
COMM : "Community Coin",
COOL : "CoolCoin",
CRACK : "CrackCoin",
"CRC*" : "CraftCoin",
CRYPT : "CryptCoin",
DEM : "eMark",
DMD : "Diamond",
XVG : "Verge",
DRKC : "DarkCash",
DSB : "DarkShibe",
DVC : "DevCoin",
EAC : "EarthCoin",
EFL : "E-Gulden",
ELC : "Elacoin",
EMC2 : "Einsteinium",
EMD : "Emerald",
EXCL : "Exclusive Coin",
EXE : "ExeCoin",
EZC : "EZCoin",
FLAP : "Flappy Coin",
FC2 : "Fuel2Coin",
FFC : "FireflyCoin",
FIBRE : "FIBRE",
FRC : "FireRoosterCoin",
FLT : "FlutterCoin",
FRK : "Franko",
FRAC : "FractalCoin",
FST : "FastCoin",
FTC : "FeatherCoin",
GDC : "GrandCoin",
GLC : "GlobalCoin",
GLD : "GoldCoin",
GLX : "GalaxyCoin",
GLYPH : "GlyphCoin",
GML : "GameLeagueCoin",
GUE : "GuerillaCoin",
HAL : "Halcyon",
HBN : "HoboNickels",
HUC : "HunterCoin",
HVC : "HeavyCoin",
HYP : "Hyperstake",
ICB : "IceBergCoin",
IFC : "Infinite Coin",
IOC : "IOCoin",
IXC : "IXcoin",
JBS : "JumBucks Coin",
JKC : "JunkCoin",
JUDGE : "JudgeCoin",
KDC : "Klondike Coin",
"KEY*" : "KeyCoin",
KGC : "KrugerCoin",
"LAB*" : "CoinWorksCoin",
"LGD*" : "Legendary Coin",
LK7 : "Lucky7Coin",
LKY : "LuckyCoin",
LSD : "LightSpeedCoin",
LTB : "Litebar ",
LTCD : "LitecoinDark",
LTCX : "LitecoinX",
LXC : "LibrexCoin",
LYC : "LycanCoin",
MAX : "MaxCoin",
MEGA : "MegaFlash",
VRS : "Veros",
ALC : "Arab League Coin",
DOGETH : "EtherDoge",
KLC : "KiloCoin",
HUSH : "Hush",
BTLC : "BitLuckCoin",
DRM8 : "Dream8Coin",
FIST : "FistBump",
EBZ : "Ebitz",
DRS : "Digital Rupees",
FGZ : "Free Game Zone",
BOSON : "BosonCoin",
ATX : "ArtexCoin",
PNC : "PlatiniumCoin",
BRDD : "BeardDollars",
TIME : "Time",
BIP : "BipCoin",
XNC : "XenCoin",
EMB : "EmberCoin",
BTTF : "Coin to the Future",
DLR : "DollarOnline",
CSMIC : "Cosmic",
FIRST : "FirstCoin",
SCASH : "SpaceCash",
XEN : "XenixCoin",
JIO : "JIO Token",
IW : "iWallet",
JNS : "Janus",
TRICK : "TrickyCoin",
DCRE : "DeltaCredits",
FRE : "FreeCoin",
NPC : "NPCcoin",
PLNC : "PLNCoin",
DGMS : "Digigems",
ICOB : "Icobid",
ARCO : "AquariusCoin",
KURT : "Kurrent",
XCRE : "Creatio",
ENT : "Eternity",
UR : "UR",
MTLM3 : "Metal Music v3",
ODNT : "Old Dogs New Tricks",
EUC : "Eurocoin",
CCX : "CoolDarkCoin",
BCF : "BitcoinFast",
SEEDS : "SeedShares",
XSN : "Stakenet",
TKS : "Tokes",
BCCOIN : "BitConnect Coin",
SHORTY : "ShortyCoin",
PCM : "Procom",
KC : "Kernalcoin",
CORAL : "CoralPay",
BamitCoin : "BAM",
NXC : "Nexium",
MONEY : "MoneyCoin",
BSTAR : "Blackstar",
HSP : "Horse Power",
HZT : "HazMatCoin",
CS : "CryptoSpots",
XSP : "PoolStamp",
CCRB : "CryptoCarbon",
BULLS : "BullshitCoin",
INCNT : "Incent",
ICON : "Iconic",
NIC : "NewInvestCoin",
ACN : "AvonCoin",
XNG : "Enigma",
XCI : "Cannabis Industry Coin",
LOOK : "LookCoin",
LOC : "Loco",
MMXVI : "MMXVI",
MIS : "MIScoin",
WOP : "WorldPay",
CQST : "ConquestCoin",
IMPS : "Impulse Coin",
IN : "InCoin",
CHIEF : "TheChiefCoin",
GOAT : "Goat",
ANAL : "AnalCoin",
RC : "Russiacoin",
PND : "PandaCoin",
PX : "PXcoin",
"CND*" : "Canada eCoin",
OPTION : "OptionCoin",
AV : "Avatar Coin",
LTD : "Limited Coin",
UNITS : "GameUnits",
HEEL : "HeelCoin",
GAKH : "GAKHcoin",
SHIFT : "Shift",
S8C : "S88 Coin",
LVG : "Leverage Coin",
DRA : "DraculaCoin",
ASAFE2 : "Allsafe",
LTCR : "LiteCreed",
QBC : "Quebecoin",
XPRO : "ProCoin",
"AST*" : "Astral",
GIFT : "GiftNet",
VIDZ : "PureVidz",
INC : "Incrementum",
PTA : "PentaCoin",
ACID : "AcidCoin",
ZLQ : "ZLiteQubit",
RADI : "RadicalCoin",
RNC : "ReturnCoin",
GOLOS : "Golos",
PASC : "Pascal Coin",
TWIST : "TwisterCoin",
PAYP : "PayPeer",
DETH : "DarkEther",
YAY : "YAYcoin",
YES : "YesCoin",
LENIN : "LeninCoin",
MRSA : "MrsaCoin",
OS76 : "OsmiumCoin",
BOSS : "BitBoss",
BIC : "Bikercoins",
CRPS : "CryptoPennies",
MOTO : "Motocoin",
NTCC : "NeptuneClassic",
"XNC*" : "Numismatic Collections",
HXX : "HexxCoin",
SPKTR : "Ghost Coin",
MAC : "MachineCoin",
SEL : "SelenCoin",
NOO : "Noocoin",
CHAO : "23 Skidoo",
XGB : "GoldenBird",
YMC : "YamahaCoin",
JOK : "JokerCoin",
GBIT : "GravityBit",
TEC : "TeCoin",
BOMB : "BombCoin",
RIDE : "Ride My Car",
PIVX : "Private Instant Verified Transaction",
KED : "Klingon Empire Darsek",
CNO : "Coino",
WEALTH : "WealthCoin",
IOP : "Internet of People",
XSPEC : "Spectre",
PEPECASH : "Pepe Cash",
CLICK : "Clickcoin",
ELS : "Elysium",
KUSH : "KushCoin",
ERY : "Eryllium",
PRES : "President Trump",
BTZ : "BitzCoin",
OPES : "Opes",
WCT : "Waves Community Token",
UBQ : "Ubiq",
RATIO : "Ratio",
BAN : "Babes and Nerds",
NICE : "NiceCoin",
SMF : "SmurfCoin",
CWXT : "CryptoWorldXToken",
TECH : "TechCoin",
CIR : "CircuitCoin",
LEPEN : "LePenCoin",
ROUND : "RoundCoin",
MAR : "MarijuanaCoin",
MARX : "MarxCoin",
TAT : "Tatiana Coin",
HAZE : "HazeCoin",
PRX : "Printerium",
NRC : "Neurocoin",
PAC : "PacCoin",
IMPCH : "Impeach",
ERR : "ErrorCoin",
TIC : "TrueInvestmentCoin",
NUKE : "NukeCoin",
EOC : "EveryonesCoin",
SFC : "Solarflarecoin",
JANE : "JaneCoin",
PARA : "ParanoiaCoin",
MM : "MasterMint",
NDOGE : "NinjaDoge",
ZBC : "Zilbercoin",
FRST : "FirstCoin",
PAY : "TenX",
ORO : "OroCoin",
ALEX : "Alexandrite",
TBCX : "TrashBurn",
MCAR : "MasterCar",
THS : "TechShares",
ACES : "AcesCoin",
UAEC : "United Arab Emirates Coin",
EA : "EagleCoin",
PIE : "Persistent Information Exchange",
CREA : "CreativeChain",
WISC : "WisdomCoin",
BVC : "BeaverCoin",
FIND : "FindCoin",
MLITE : "MeLite",
STALIN : "StalinCoin",
TSE : "TattooCoin",
VLTC : "VaultCoin",
BIOB : "BioBar",
PASL : "Pascal Lite",
ZER : "Zero",
CHAT : "ChatCoin",
CDN : "Canada eCoin",
TPAY : "TrollPlay",
NETKO : "Netko",
ZOI : "Zoin",
HONEY : "Honey",
MXT : "MartexCoin",
MUSIC : "Musicoin",
DTB : "Databits",
VEG : "BitVegan",
MBIT : "Mbitbooks",
VOLT : "BitVolt",
"B@" : "BankCoin",
BEST : "BestChain",
CHC : "ChainCoin",
ZENI : "Zennies",
PLANET : "PlanetCoin",
DUCK : "DuckDuckCoin",
BNX : "BnrtxCoin",
BSTK : "BattleStake",
RNS : "RenosCoin",
DBIX : "DubaiCoin",
AMIS : "AMIS",
KAYI : "Kayı",
XVP : "VirtacoinPlus",
BOAT : "Doubloon",
TAJ : "TajCoin",
IMX : "Impact",
CJC : "CryptoJournal",
AMY : "Amygws",
QBT : "Cubits",
"SRC*" : "StarCredits",
EB3 : "EB3coin",
XVE : "The Vegan Initiative",
FAZZ : "FazzCoin",
APT : "Aptcoin",
BLAZR : "BlazerCoin",
ARPA : "ArpaCoin",
"BNB*" : "Boats and Bitches",
UNI : "Universe",
ECO : "ECOcoin",
XLR : "Solaris",
DARK : "Dark",
DON : "DonationCoin",
MER : "Mercury",
WGO : "WavesGO",
ATMOS : "Atmos",
INPAY : "InPay",
ETT : "EncryptoTel",
"WBTC*" : "wBTC",
VISIO : "Visio",
HPC : "HappyCoin",
GOT : "Giotto Coin",
CXT : "Coinonat",
EMPC : "EmporiumCoin",
LGD : "Legends Cryptocurrency",
BUCKS : "SwagBucks",
XBY : "XtraBYtes",
GUP : "Guppy",
MCRN : "MacronCoin",
RAIN : "Condensate",
WSX : "WeAreSatoshi",
IEC : "IvugeoEvolutionCoin",
IMS : "Independent Money System",
ARGUS : "ArgusCoin",
CNT : "Centurion",
LMC : "LomoCoin",
BTCS : "Bitcoin Scrypt",
PROC : "ProCurrency",
XGR : "GoldReserve",
"WRC*" : "WarCoin",
BENJI : "BenjiRolls",
DUO : "ParallelCoin",
RBX : "RiptoBuX",
GRW : "GrowthCoin",
APX : "Apx",
MILO : "MiloCoin",
OLV : "OldV",
ILC : "ILCoin",
MRT : "MinersReward",
IOU : "IOU1",
PZM : "Prizm",
PHR : "Phreak",
PUPA : "PupaCoin",
RICE : "RiceCoin",
XCT : "C-Bits",
DEA : "Degas Coin",
RED : "Redcoin",
ZSE : "ZSEcoin",
CTIC : "Coinmatic",
TAP : "TappingCoin",
BITOK : "BitOKX",
PBT : "Primalbase",
MUU : "MilkCoin",
INF8 : "Infinium-8",
HTML5 : "HTML5 Coin",
MNE : "Minereum",
DICE : "Etheroll",
"SUB*" : "Subscriptio",
USC : "Ultimate Secure Cash",
DUX : "DuxCoin",
XPS : "PoisonIvyCoin",
EQT : "EquiTrader",
INSN : "Insane Coin",
"MAT*" : "Manet Coin",
F16 : "F16Coin",
HAMS : "HamsterCoin",
QTUM : "QTUM",
NEF : "NefariousCoin",
ZEN : "ZenCash",
BOS : "BOScoin",
QWARK : "Qwark",
IOT : "IOTA",
ADL : "Adelphoi",
"ECC*" : "E-CurrencyCoin",
ZRC : "ZrCoin",
LKK : "Lykke",
ESP : "Espers",
"MAD*" : "SatoshiMadness",
DYN : "Dynamic",
SEQ : "Sequence",
MCAP : "MCAP",
SKY : "Skycoin",
CFI : "Cofound.it",
IXT : "iXledger",
STA : "Starta",
EFYT : "Ergo",
XTZ : "Tezos",
QAU : "Quantum",
ECOB : "EcoBit",
USDT : "Tether",
NANO : "Nano",
AHT : "Ahoolee",
ATB : "ATB coin",
CHAN : "ChanCoin",
CMP : "Compcoin",
HRB : "Harbour DAO",
ACT : "ACT",
"8BT" : "8 Circuit Studios",
SUR : "Suretly",
PING : "CryptoPing",
MIV : "MakeItViral",
WGR : "Wagerr",
XEL : "Elastic",
NVST : "NVO",
FUNC : "FunCoin",
PQT : "PAquarium",
SNC : "SunContract",
STAR : "Starbase",
COR : "Corion",
OROC : "Orocrypt",
OAX : "OpenANX",
MBI : "Monster Byte Inc",
DDF : "Digital Developers Fund",
DIM : "DIMCOIN",
GGS : "Gilgam",
DNA : "EncrypGen",
FYN : "FundYourselfNow",
FND : "FundRequest",
DCY : "Dinastycoin",
CFT : "CryptoForecast",
DNR : "Denarius",
DP : "DigitalPrice",
VUC : "Virta Unique Coin",
BTPL : "Bitcoin Planet",
UNIFY : "Unify",
IPC : "ImperialCoin",
BRIT : "BritCoin",
AMMO : "Ammo Rewards",
SOCC : "SocialCoin",
MASS : "Mass.Cloud",
LA : "LATOKEN",
IML : "IMMLA",
XUC : "Exchange Union",
STU : "BitJob",
GUNS : "GeoFunders",
SYC : "SynchroCoin",
"AHT*" : "Bowhead Health",
TRIBE : "TribeToken",
NPX : "Napoleon X",
SCORE : "Scorecoin",
OTX : "Octanox",
EQB : "Equibit",
CVCOIN : "Crypviser",
ARC : "ArcticCoin",
BOG : "Bogcoin",
ADT : "AdToken",
UET : "Useless Ethereum Token",
PART : "Particl",
AGRS : "Agoras Token",
SAND : "BeachCoin",
"XAI*" : "AICoin",
DMT : "DMarket",
DAS : "DAS",
XCJ : "CoinJob",
RKC : "Royal Kingdom Coin",
NLC2 : "NoLimitCoin",
LINDA : "Linda",
SPN : "Spoon",
KING : "King93",
ANCP : "Anacrypt",
RCC : "Reality Clash",
ROOTS : "RootProject",
SNK : "Sosnovkino",
CABS : "CryptoABS",
ZNT : "OpenZen",
BITSD : "Bits Digit",
XLC : "LeviarCoin",
SKIN : "Skincoin",
HIRE : "HireMatch",
"BBT*" : "BrickBlock",
DFBT : "DentalFix",
EQ : "EQUI",
WLK : "Wolk",
VIB : "Viberate",
ONION : "DeepOnion",
BTX : "Bitcore",
ICE : "iDice",
XID : "Sphre AIR",
GCN : "gCn Coin",
"ATOM*" : "Cosmos",
ICOO : "ICO OpenLedger",
TME : "Timereum",
SIGT : "Signatum",
ONX : "Onix",
COE : "CoEval",
ARENA : "Arena",
WINK : "Wink",
CRM : "Cream",
BCH : "Bitcoin Cash",
DGPT : "DigiPulse",
MOBI : "Mobius",
SDAO : "Solar DAO",
CORE : "Core Group Asset",
KEN : "Kencoin",
QVT : "Qvolta",
AUT : "Autoria",
CTT : "CodeTract",
GRWI : "Growers International",
MNY : "Monkey",
MTH : "Monetha",
CCC : "CCCoin",
UMC : "Umbrella Coin",
BMXT : "Bitmxittz",
GAS : "Gas",
FIL : "FileCoin",
OCL : "Oceanlab",
BNC : "Benjacoin",
TOM : "Tomahawkcoin",
XAS : "Asch",
SMNX : "SMNX",
DLT : "Agrello Delta",
MRV : "Macroverse",
MBRS : "Embers",
MET : "Memessenger",
NEBL : "Neblio",
PGL : "Prospectors",
XMCC : "Monoeci",
AUN : "Authoreon",
"CASH*" : "Cash Poker Pro",
CMPCO : "CampusCoin",
DTCT : "DetectorToken",
WNET : "Wavesnode.net",
THNX : "ThankYou",
WORM : "HealthyWorm",
VNT : "Veredictum",
SIFT : "Smart Investment Fund Token",
IGNIS : "Ignis",
IWT : "IwToken",
JDC : "JustDatingSite",
ITT : "Intelligent Trading",
LNC : "BlockLancer",
AIX : "Aigang",
XEC : "Eternal Coin",
ENTRP : "Entropy Token",
ICOS : "ICOBox",
PIX : "Lampix",
MEDI : "MediBond",
LTA : "Litra",
NIMFA : "Nimfamoney",
SCOR : "Scorista",
MLS : "CPROP",
KEX : "KexCoin",
BRO : "Bitradio",
MINEX : "Minex",
"MAG*" : "Magos",
DFT : "Draftcoin",
LAT : "Latium",
SOJ : "Sojourn Coin",
STCN : "Stakecoin",
SQP : "SqPay",
RIYA : "Etheriya",
LNK : "Ethereum.Link",
WAN : "Wanchain",
MNTP : "GoldMint",
ALTOCAR : "AltoCar",
"CFT*" : "Credo",
BLX : "Blockchain Index",
BOU : "Boulle",
OXY : "Oxycoin",
TTT : "Tap Project",
AMT : "Acumen",
GIM : "Gimli",
NYC : "NewYorkCoin",
LBTC : "LiteBitcoin",
FRAZ : "FrazCoin",
EMT : "EasyMine",
GXC : "Gx Coin",
KRONE : "Kronecoin",
SRT : "Scrypto",
AVA : "Avalon",
BT : "BuildTeam",
ACC : "AdCoin",
"AR*" : "Ar.cash",
Z2 : "Z2 Coin",
LINX : "Linx",
XCXT : "CoinonatX",
BLAS : "BlakeStar",
GOOD : "GoodCoin",
TRV : "Travel Coin",
CRTM : "Cryptum",
EON : "Exscudo",
CTX : "CarTaxi",
CNX : "Cryptonex",
DRC : "Dropcoin",
ACE : "TokenStars",
BRX : "Breakout Stake",
UCASH : "U.CASH",
WRT : "WRTcoin",
ORME : "Ormeus Coin",
DEEP : "Deep Gold",
"TMT*" : "ToTheMoon",
CCT : "Crystal Clear Token ",
WSH : "Wish Finance",
"ARNA*" : "ARNA Panacea",
ABC : "AB-Chain",
PRP : "Papyrus",
"SKR*" : "Skrilla Token",
"3DES" : "3DES",
PYN : "Paycentos",
KAPU : "Kapu",
CAPP : "Cappasity",
FC : "Facecoin",
RCN : "Ripio",
NRN : "Doc.ai Neuron",
WIZ : "Crowdwiz",
ATKN : "A-Token",
RUSTBITS : "Rustbits",
ETHD : "Ethereum Dark",
SUMO : "Sumokoin",
H2O : "Hydrominer",
TKT : "Crypto Tickets",
RHEA : "Rhea",
MTN : "TrackNetToken",
STOCKBET : "StockBet",
PLM : "Algo.Land",
SND : "Sandcoin",
XP : "Experience Points",
HSR : "Hshare",
ZNA : "Zenome",
EZM : "EZMarket",
ODN : "Obsidian",
MTK : "Moya Token",
CAS : "Cashaa",
MAT : "MiniApps",
GJC : "Global Jobcoin",
WIC : "Wi Coin",
WAND : "WandX",
ELIX : "Elixir",
EBTC : "eBitcoin",
ADA : "Cardano",
REC : "Regalcoin",
BIS : "Bismuth",
OPP : "Opporty",
ROCK : "Ice Rock Mining",
EARTH : "Earth Token",
VSX : "Vsync",
"WISH*" : "WishFinance",
FLASH : "FLASH coin",
GRFT : "Graft Blockchain",
BTCZ : "BitcoinZ",
CZC : "Crazy Coin",
GUESS : "Peerguess",
ETP : "Metaverse",
CIX : "Cryptonetix",
ERT : "Esports.com",
"BAC*" : "LakeBanker",
FLIK : "FLiK",
MBT : "Multibot",
JVY : "Javvy",
ARBI : "Arbi",
ELT : "Eloplay",
ARN : "Aeron",
ROK : "Rockchain",
XRED : "X Real Estate Development",
DAY : "Chronologic",
HXT : "HextraCoin",
"VRP*" : "Prosense.tv",
NTM : "NetM",
TZC : "TrezarCoin",
MCI : "Musiconomi",
NTO : "Fujinto",
ATCC : "ATC Coin",
KOLION : "Kolion",
WILD : "Wild Crypto",
ELTC2 : "eLTC",
ILCT : "ILCoin Token",
RYZ : "Anryze",
"GXC*" : "GenXCoin",
ELM : "Elements",
TER : "TerraNovaCoin",
XCS : "CybCSec Coin",
BQ : "Bitqy",
CAV : "Caviar",
CLOUT : "Clout",
"PTC*" : "Propthereum",
EVR : "Everus",
TOA : "TOA Coin",
MNZ : "Monaize",
VIVO : "VIVO Coin",
RPX : "Red Pulse",
AURS : "Aureus",
CAG : "Change",
ECHT : "e-Chat",
INXT : "Internxt",
ATS : "Authorship",
RGC : "RG Coin",
EBET : "EthBet",
"BM*" : "Bitcomo",
WHL : "WhaleCoin",
BTG : "Bitcoin Gold",
ETG : "Ethereum Gold",
WOMEN : "WomenCoin",
MAY : "Theresa May Coin",
RNDR : "Render Token",
EDDIE : "Eddie coin",
"SCT*" : "Soma",
NAMO : "NamoCoin",
KCS : "Kucoin",
FLLW : "Follow Coin",
WYR : "Wyrify",
VZT : "Vezt",
INDI : "IndiCoin",
LUX : "LUXCoin",
BAR : "TBIS token",
PIRL : "Pirl",
ECASH : "Ethereum Cash",
ODMC : "ODMCoin",
"CABS*" : "CyberTrust",
BRAT : "BROTHER",
DTR : "Dynamic Trading Rights",
TKR : "CryptoInsight",
ELITE : "EthereumLite",
XIOS : "Xios",
DOVU : "DOVU",
ETN : "Electroneum",
REA : "Realisto",
AVE : "Avesta",
XNN : "Xenon",
BTDX : "Bitcloud 2.0",
"LOAN*" : "Lendoit",
"DTT*" : "Data Trading",
ZAB : "ZABERcoin",
"MDL*" : "Modulum",
BT1 : "Bitfinex Bitcoin Future",
BT2 : "Bitcoin SegWit2X",
JCR : "Jincor",
XSB : "Extreme Sportsbook",
EBST : "eBoost",
KEK : "KekCoin",
"BHC*" : "BlackholeCoin",
ALTCOM : "AltCommunity Coin",
OST : "Simple Token",
UGC : "ugChain",
DTC : "Datacoin",
PURE : "Pure",
CLD : "Cloud",
POS : "PoSToken",
NEOG : "NEO Gold",
EXN : "ExchangeN",
TRCT : "Tracto",
BTCRED : "Bitcoin Red",
EBCH : "eBitcoinCash",
JTX : "Project J",
AXT : "AIX",
NEU : "Neumark",
RUPX : "Rupaya",
BDR : "BlueDragon",
XIN : "Infinity Economics",
DUTCH : "Dutch Coin",
"HNC*" : "Huncoin",
"MDC*" : "MadCoin",
PURA : "Pura",
INN : "Innova",
BDL : "Bitdeal",
CMS : "COMSA",
XBL : "Billionaire Token",
ZEPH : "Project Zephyr",
ATFS : "ATFS Project",
GES : "Galaxy eSolutions",
"PHR*" : "Phore",
LCASH : "LitecoinCash",
CFD : "Confido",
PLC : "PlusCoin",
SRN : "SirinLabs",
WSC : "WiserCoin",
XGOX : "Go!",
NEWB : "Newbium",
LIFE : "LIFE",
RMC : "Russian Mining Coin",
MSR : "Masari",
CJT : "ConnectJob Token",
"ESC*" : "Ethersportcoin",
BNK : "Bankera",
ELLA : "Ellaism",
BPL : "BlockPool",
DRXNE : "Droxne",
SKR : "Sakuracoin",
XPTX : "PlatinumBAR",
GVT : "Genesis Vision",
GMT : "Mercury Protocol",
"EPY*" : "Emphy",
"HOLD*" : "Interstellar Holdings",
MNX : "MinexCoin",
CRDS : "Credits",
VIU : "Viuly",
"SCR*" : "Scorum",
DBR : "Düber",
ABT : "Advanced Browsing Token",
GFT : "Giftcoin",
STAC : "STAC",
RIPT : "RiptideCoin",
BBT : "BitBoost",
GBX : "GoByte",
CSTL : "Castle",
ICC : "Insta Cash Coin",
ALQO : "Alqo",
"KNC**" : "KingN Coin",
TRIA : "Triaconta",
MAG : "Magnet",
STEX : "STEX",
TAU : "Lamden Tau",
LAB : "Labrys",
FRD : "Farad",
ECA : "Electra",
LDM : "Ludum token",
LTG : "LiteCoin Gold",
BCD : "Bitcoin Diamond",
STP : "StashPay",
AERM : "Aerium",
PLX : "PlexCoin",
ETHB : "EtherBTC",
CDX : "Commodity Ad Network",
FOOD : "FoodCoin",
VOT : "Votecoin",
SETH : "Sether",
"TIO*" : "Tio Tour Guides",
ABYSS : "The Abyss",
XSH : "SHIELD",
"BCD*" : "BitCAD",
GEA : "Goldea",
"BCO*" : "BridgeCoin",
DSR : "Desire",
ONG : "onG.social",
BTCM : "BTCMoon",
ETBT : "Ethereum Black",
ZCG : "ZCashGOLD",
MUT : "Mutual Coin",
MEOW : "Kittehcoin",
DIVX : "Divi",
CNBC : "Cash & Back Coin",
"ARC*" : " Arcade City",
XUN : "UltraNote",
RFL : "RAFL",
ELTCOIN : "ELTCOIN",
GRX : "Gold Reward Token",
NTK : "Neurotoken",
ERO : "Eroscoin",
MAN : "People",
CWV : "CryptoWave",
"ACT*" : "Achain",
NRO : "Neuro",
SEND : "Social Send",
GLT : "GlobalToken",
COAL : "BitCoal",
DAXX : "DaxxCoin",
BWK : "Bulwark",
FNTB : "FinTab",
XMRG : "Monero Gold",
BTCE : "EthereumBitcoin",
BOXY : "BoxyCoin",
UTN : "Universa",
EGAS : "ETHGAS",
DPP : "Digital Assets Power Play",
BMT : "BMChain",
BIO : "Biocoin",
MTRC : "ModulTrade",
BTCL : "BTC Lite",
PCN : "PeepCoin",
PYP : "PayPro",
RBTC : "Bitcoin Revolution",
CRED : "Verify",
SBTC : "Super Bitcoin",
KLKS : "Kalkulus",
AC3 : "AC3",
GTO : "GIFTO",
TNB : "Time New Bank",
"CHIPS*" : "CHIPS",
"LOC*" : "LockTrip",
"MNT*" : "Media Network Coin",
ITNS : "IntenseCoin",
"SMT*" : "SmartMesh",
GER : "GermanCoin",
LTCU : "LiteCoin Ultra",
EMGO : "MobileGo",
BTCA : "Bitair",
HQX : "HOQU",
ETF : "EthereumFog",
"BCX*" : "BitcoinX",
"LUX**" : "Luxmi Coin",
STAK : "Straks",
BCOIN : "BannerCoin",
"MED*" : "MediBloc",
CCOS : "CrowdCoinage",
HAT : "Hawala.Today",
VLR : "Valorem",
CWX : "Crypto-X",
DBC : "DeepBrain Chain",
"ZEN*" : "Zen Protocol",
POP : "PopularCoin",
"CRC***" : "CrowdCoin",
PNX : "PhantomX",
BAS : "BitAsean",
HBC : "HomeBlockCoin",
AMM : "MicroMoney",
DAV : "DavorCoin",
XCPO : "Copico",
GENE : "PARKGENE",
NMS : "Numus",
PHO : "Photon",
XTRA : "ExtraCredit",
HION : "Handelion",
NTWK : "Network Token",
SUCR : "Sucre",
"SMART*" : "SmartBillions",
ACCO : "Accolade",
BTH : "Bytether ",
REM : "REMME",
TOK : "TokugawaCoin",
EREAL : "eREAL",
CPN : "CompuCoin",
XFT : "Fantasy Cash",
QLC : "QLC Chain",
BTSE : "BitSerial",
OMGC : "OmiseGO Classic",
Q2C : "QubitCoin",
BLT : "Bloom Token",
TDS : "TokenDesk",
ORE : "Galactrum",
SPK : "Sparks",
GOA : "GoaCoin",
FLS : "Fuloos Coin",
WAGE : "Digiwage",
GUN : "GunCoin",
DFS : "DFSCoin",
POLIS : "PolisPay",
WELL : "Well",
FLOT : "FireLotto",
CL : "CoinLancer",
SHND : "StrongHands",
AUA : "ArubaCoin",
SAGA : "SagaCoin",
GXS : "GXChain",
TSL : "Energo",
IRL : "IrishCoin",
BOT : "Bodhi",
PMA : "PumaPay",
TROLL : "Trollcoin",
FOR : "Force Coin",
SGR : "Sugar Exchange",
JET : "Jetcoin",
MDS : "MediShares",
LCP : "Litecoin Plus",
IETH : "iEthereum",
"GCC*" : "TheGCCcoin",
INK : "Ink",
KBR : "Kubera Coin",
JINN : "Jinn",
SET : "Setcoin",
MGN : "MagnaCoin",
KZC : "KZCash",
GNR : "Gainer",
LWF : "Local World Forwarders",
BRC : "BrightCoin",
WCG : "World Crypto Gold",
HIVE : "Hive",
GX : "GameX",
ETL : "EtherLite",
DRG : "Dragon Coin",
"BRC*" : "BinaryCoin",
"SPX*" : "Sp8de",
AIDOC : "AI Doctor",
ECC : "ECC",
ET4 : "Eticket4",
LCT : "LendConnect",
VST : "Vestarin",
STN : "Steneum Coin",
SFU : "Saifu",
PCOIN : "Pioneer Coin",
"BLN*" : "Bolenum",
LUC : "Play 2 Live",
EDT : "EtherDelta",
CYDER : "Cyder Coin",
SRNT : "Serenity",
MLT : "MultiGames",
UBTC : "UnitedBitcoin",
BTO : "Bottos",
DOC : "Doc Coin",
ARCT : "ArbitrageCT",
IDH : "IndaHash",
ITZ : "Interzone",
XBP : "Black Pearl Coin",
EXRN : "EXRNchain",
BFT : "BF Token",
SGL : "Sigil",
TNC : "Trinity Network Credit",
CFTY : "Crafty",
DTA : "Data",
CV : "CarVertical",
DTX : "DataBroker DAO",
MCU : "MediChain",
OCN : "Odyssey",
PRPS : "Purpose",
DUBI : "Decentralized Universal Basic Income",
BPT : "Blockport",
SGN : "Signals Network",
TCT : "TokenClub ",
ZIL : "Zilliqa",
"QBT*" : "Qbao",
"ACC*" : "Accelerator Network",
SWFTC : "SwftCoin",
OPC : "OP Coin",
SAF : "Safinus",
SHA : "Shacoin",
PYLNT : "Pylon Network",
GRLC : "Garlicoin",
REPUX : "Repux",
JOY : "JoyToken",
"GTC*" : "Global Tour Coin",
"XCD*" : "Capdax",
BTW : "BitcoinWhite",
AXP : "aXpire",
FOTA : "Fortuna",
DDD : "Scry.info",
SPEND : "Spend",
ZPT : "Zeepin",
CROAT : "Croat",
REF : "RefToken",
LDC : "LeadCoin",
"FAIR*" : "FairGame",
VAL : "Valorbit",
BCDN : "BlockCDN ",
STK : "STK Token",
MZX : "Mosaic Network",
"CRC**" : "CryCash",
SPICE : "SPiCE Venture Capital ",
Q1S : "Quantum1Net",
XTO : "Tao",
ELA : "Elastos",
"TPAY*" : "TokenPay",
CXO : "CargoX",
WT : "WeToken",
HGS : "HashGains",
SISA : "Strategic Investments in Significant Areas",
EBIT : "eBit",
CUZ : "Cool Cousin",
HLC : "Halal-Chain",
GMR : "Gimmer",
ING : "Iungo",
LHC : "LHCoin",
BLZ : "Bluzelle",
HALAL : "Halal",
"CRAVE*" : "Crave-NG",
CHSB : "SwissBorg",
EQUI : "EQUI Token",
MCT : "1717 Masonic Commemorative Token",
HHEM : "Healthureum",
CWIS : "Crypto Wisdom Coin",
MBC : "My Big Coin",
GRO : "Gron Digital",
"MTN*" : "Medicalchain",
WBTC : "WorldBTC",
DNO : "Denaro",
eFIC : "FIC Network",
TKY : "THEKEY Token",
TRTL : "TurtleCoin",
"CARE*" : "Care Token",
DRPU : "DRP Utility",
DOR : "Dorado",
PRFT : "Proof Suite Token",
DTRC : "Datarius",
IQB : "Intelligence Quotient Benefit",
"NDC*" : "NeedleCoin",
MUN : "MUNcoin",
TIG : "Tigereum",
NYX : "NYXCOIN",
SAT : "Satisfaction Token",
CRL : "Cryptelo Coin",
ORI : "Origami",
LYM : "Lympo",
USX : "Unified Society USDEX",
LGR : "Logarithm",
BCA : "Bitcoin Atom",
B2X : "SegWit2x",
EXMR : "eXMR Monero",
UETL : "Useless Eth Token Lite",
NBR : "Niobio Cash",
RAVE : "Ravelous",
ILT : "iOlite",
SCOOBY : "Scooby coin",
CEFS : "CryptopiaFeeShares",
"MINT*" : "Mineable Token",
BUN : "BunnyCoin",
BSR : "BitSoar Coin",
SKULL : "Pirate Blocks",
TRDT : "Trident",
XBTY : "Bounty",
JC : "JesusCoin",
BTCP : "Bitcoin Private",
SKC : "Skeincoin",
MWAT : "RED MegaWatt",
JEW : "Shekel",
"ERT*" : "Eristica",
KRM : "Karma",
CDY : "Bitcoin Candy",
SSS : "ShareChain",
CRDNC : "Credence Coin",
BIFI : "BitcoinFile",
BTF : "Blockchain Traded Fund",
"IPC*" : "IPChain",
SHOW : "ShowCoin",
STC : "StarChain",
AIT : "AIChain Token",
ALT : "ALTcoin",
TRF : "Travelflex",
KB3 : "B3Coin",
FDX : "fidentiaX",
KREDS : "KREDS",
EQL : "EQUAL",
GAI : "GraphGrail AI",
VULC : "Vulcano",
"CRE*" : "Creditcoin",
"DTC**" : "DivotyCoin",
DADI : "DADI",
"MAG**" : "Maggie Token",
TOKC : "Tokyo Coin",
UNRC : "UniversalRoyalCoin",
BBP : "BiblePay",
NOX : "NITRO",
HYS : "Heiss Shares",
LCWP : "LiteCoinW Plus",
"FLX*" : "BitFlux",
VVI : "VV Coin",
ANK : "Ankorus Token",
HLP : "Purpose Coin",
VIN : "VinChain",
SHPING : "Shping Coin",
PTR : "Petro",
LCC : "LitecoinCash",
"BCR*" : "Bitcoin Royal",
VANY : "Vanywhere",
NBX : "Noxbox",
BAX : "BABB",
"SPC*" : "SpaceChain",
FLIP : "BitFlip",
CLIN : "Clinicoin",
DHT : "DeHedge Token",
"GOOD*" : "Goodomy",
SOC : "All Sports Coin",
TDX : "Tidex Token",
LOT : "LottoCoin",
FUNK : "Cypherfunks Coin",
LEAF : "LeafCoin",
COMP : "Compound Coin",
BITCAR : "BitCar",
NIHL : "Nihilo Coin",
BASHC : "BashCoin",
DIGIF : "DigiFel",
DGM : "DigiMoney",
CBS : "Cerberus",
TERN : "Ternio",
SVD : "Savedroid",
PF : "PROVER",
BTCH : "Bitcoin Hush",
redBUX : "redBUX",
LIZ : "Lizus Payment",
CIF : "Crypto Improvement Fund",
SPD : "Stipend",
"PUT*" : "Robin8 Profile Utility Token",
FILL : "Fillit",
POA : "Poa Network",
RVN : "Ravencoin",
RFR : "Refereum",
PROPS : "Props",
CEDEX : "CEDEX Coin",
FUND : "Fund Platform",
CEL : "Celsius Network",
PUSHI : "Pushi",
BINS : "Bitsense",
POKER : "PokerCoin",
AXYS : "Axys",
"EVN*" : "EvenCoin",
BOLD : "Bold",
EXTN : "Extensive Coin",
DIG : "Dignity",
ETS : "ETH Share",
LIPC : "LIpcoin",
HELL : "HELL COIN",
ELP : "Ellerium",
ACAT : "Alphacat",
CO2 : "CO2 Token",
INVOX : "Invox Finance",
VLX : "Velox",
ACTN : "Action Coin",
LTCH : "Litecoin Cash",
ZUP : "Zupply Token",
HMT : "Hamster Marketplace Token",
MDX : "Midex",
USDC : "USCoin",
CBC : "CashBagCoin",
BCT : "Blockchain Terminal",
CLO : "Callisto Network",
CRU : "Curium",
"ELI*" : "Elicoin",
MOAT : "Mother Of All Tokens",
BBI : "BelugaPay",
ENTRC : "ENTER COIN",
BTCGO : "BitcoinGo",
XTROPTIONS : "TROPTIONS",
KNW : "Knowledge ",
PGC : "Pegascoin",
BIT : "BitRewards",
"PTC**" : "Plutocoin",
PKC : "Pikciochain",
SQOIN : "StasyQ",
TBAR : "Titanium BAR",
TKLN : "Taklimakan",
CPL : "CoinPlace Token",
TUBE : "BitTube",
OMX : "Project Shivom",
TRCK : "Truckcoin",
CHI : "Chimaera",
"CHF*" : "MobileBridge Momentum",
W3C : "W3Coin",
DIN : "Dinero",
CHP : "CoinPoker Token",
PSD : "Poseidon",
LELE : "Lelecoin",
DROP : "Dropil",
"VEGA*" : "VEGA",
AKA : "Akroma",
SHIP : "ShipChain",
IHT : "I-House Token",
LCS : "LocalCoinSwap",
FOXT : "Fox Trading",
ETKN : "EasyToken",
ROX : "Robotina",
ADM : "Adamant",
AMBT : "AMBT Token",
"LVL*" : "LevelNet Token",
MEE : "CoinMeet",
BTRM : "Betrium Token",
MANNA : "Manna",
PROD : "Darenta",
ePRX : "eProxy",
HMC : "Hi Mutual Society",
ZIX : "ZIX Token",
ELEC : "Electrify.Asia",
ORGT : "Organic Token",
PAN : "Pantos",
BOTC : "BotChain",
GO : "GoChain",
VIEW : "Viewly",
OKOIN : "OKOIN",
ADK : "Aidos Kuneen",
GRAM : "Telegram Open Network",
ESS : "Essentia",
SERA : "Seraph",
AET : "AfterEther",
CMOS : "Cosmo",
PGN : "Pigeoncoin",
BMH : "BlockMesh",
TT : "TravelChain",
REDN : "Reden",
TLP : "TulipCoin",
BSX : "Bitspace",
"BTCE*" : "BitcoinEX",
BBN : "BBNCOIN",
TDZ : "Tradelize",
LDN : "Lydiancoin",
BUBO : "Budbo",
USOAMIC : "USOAMIC",
FLUZ : "FluzFluz",
MIO : "Miner One token",
MITH : "Mithril",
"SPD*" : "Spindle",
FNO : "Fonero",
GST : "Gostcoin",
PAS : "Passive Coin",
XSG : "Snowgem",
CVTC : "CavatCoin",
FARM : "FARM Coin",
NEXT : "Next.exchange Token",
XCLR : "ClearCoin",
"XBP*" : "BlitzPredict",
"DBC*" : "Debit Coin",
SWTH : "Switcheo",
FDZ : "Friendz",
VTN : "Voltroon",
LION : "CoinLion",
MASP : "Market.space",
XTL : "Stellite",
UCN : "UC Coin",
BRIA : "Briacoin",
IC : "Ignition",
ROI : "ROIcoin",
ETHPR : "Ethereum Premium",
MNB : "MoneyBag",
ACH : "AchieveCoin",
BTL : "Bitrolium",
GOAL : "Goal Bonanza",
HOLD : "HOLD",
EZT : "EZToken",
SOL : "Sola",
VIC : "Victorium",
XCM : "CoinMetro",
NFN : "Nafen",
WIIX : "Wiix",
EOSDAC : "eosDAC",
BCI : "Bitcoin Interest",
MEDIC : "MedicCoin",
KWH : "KWHCoin",
VLD : "Valid",
GSI : "Globex SCI",
BDP : "Bidipass",
FLM : "FOLM coin",
ALPS : "Alpenschillling",
ZEL : "Zelcash",
BKC : "Balkancoin",
BITG : "Bitcoin Green",
DEV : "Deviant Coin",
CHT : "Countinghouse Fund",
ABJ : "Abjcoin",
FTW : "FutureWorks",
RAP : "Rapture",
ARTE : "Artemine",
ANI : "Animecoin",
PHC : "Profit Hunters Coin",
ETHM : "Ethereum Meta",
NOKU : "NOKU Master token",
"RAC*" : "RoboAdvisorCoin",
PAT : "PATRON",
CHFN : "NOKU CHF",
EURN : "NOKU EUR",
LEU : "CryptoLEU",
SWC : "Scanetchain Token",
AVL : "Avalanche",
SEM : "Semux",
DARX : "Bitdaric",
BBK : "BitBlocks",
"RAC**" : "RoBET",
NCT : "PolySwarm",
UWC : "Uwezocoin",
XHV : "Haven Protocol",
CPX : "Apex Token",
ADH : "Adhive",
LIF : "Winding Tree",
EFX : "The EFFECT Network",
"MRP*" : "MoneyRebel",
FTO : "FuturoCoin",
CARE : "Carebit",
NZL : "Zealium",
TBT : "T-BOT",
XMC : "Monero Classic",
OAK : "Acorn Collective",
DML : "Decentralized Machine Learning",
TIPS : "FedoraCoin",
MOS : "MOS Coin",
PNT : "Penta",
WIN : "WCoin",
CHARM : "Charm Coin",
PROTON : "Proton",
CRS : "Cryptoreal",
DERO : "Dero",
DEAL : "iDealCash",
JUMP : "Jumpcoin",
KRL : "Kryll",
"TMT**" : "Traxia Membership Token",
"SRC**" : "SwissRealCoin",
IFX : "Infinex",
XMO : "Monero Original",
EDU : "Educoin",
PCL : "Peculium",
APH : "Aphelion",
NBAI : "Nebula AI",
TUT : "Tutellus",
ENU : "Enumivo",
BFDT : "Befund",
YUM : "Yumerium",
GSC : "Global Social Chain",
DESI : "DESI",
VLUX : "VLUX",
"MT*" : "MyToken",
SSH : "StreamSpace",
XBI : "Bitcoin Incognito",
VRA : "Verasity",
FRV : "Fitrova",
WINS : "WinStars",
RTB : "AB-CHAIN",
FXT : "FuzeX",
DXC : "DixiCoin",
CHBR : "CryptoHub",
OWD : "Owlstand",
ELLI : "ElliotCoin",
AXS : "AXS",
DAN : "Daneel",
LBA : "Libra Credit",
LIVE : "Live Stars",
GBG : "Golos Gold",
CNN : "Content Neutrality Network",
ETZ : "EtherZero",
SKM : "Skrumble Network",
SHR : "ShareRing",
KEC : "KEYCO",
ODE : "ODEM ",
AMN : "Amon",
SABR : "SABR Coin",
HWC : "HollyWoodCoin",
BITGOLD : "bitGold",
BITSILVER : "bitSilver",
GIN : "GINcoin",
OPEN : "Open Platform",
NLX : "Nullex",
FACE : "Faceter ",
IOTX : "IoTeX Network",
AITT : "AITrading",
ITM : "intimate.io",
VID : "VideoCoin",
UCT : "UCOT",
ZMR : "Monero 0",
XMV : "MoneroV",
NKN : "NKN",
ELY : "Elysian",
PAR : "Parlay",
LTCC : "Listerclassic Coin",
RST : "REGA Risk Sharing Token",
AMX : "Amero",
TFC : "The Freedom Coin",
"MSC*" : "MaisCoin",
REPO : "Repo Coin",
IRC : "IRONCOIN",
"PLC*" : "PlatinCoin",
ANGL : "Angel Token",
ANTS : "ANTS Reloaded",
KNG : "BetKings",
"AUC*" : "AU-Coin",
CMM : "Commercium ",
COG : "Cognitio",
BEN : "BitCOEN",
BCIO : "Blockchain.io",
LYL : "LoyalCoin",
FT : "Fabric Token",
PHI : "PHI Token",
PMNT : "Paymon",
BNTN : "Blocnation",
"SOUL*" : "Phantasma",
GRMD : "GreenMed",
SSC : "SelfSell",
LOKI : "Loki",
BTT : "Blocktrade token",
NCP : "Newton Coin",
MPT : "Media Protocol Token",
STAX : "Staxcoin",
MRN : "Mercoin",
FOPA : "Fopacoin",
"CBC*" : "CashBet Coin",
OOT : "Utrum",
SIC : "Swisscoin",
ALG : "Algory",
EXCC : "ExchangeCoin",
REL : "Reliance",
BTCN : "BitcoiNote",
HERO : "Hero",
EJAC : "EJA Coin",
XT3 : "Xt3ch",
MGD : "MassGrid",
VIG : "TheVig",
PLURA : "PluraCoin",
SCX : "Swachhcoin",
NWCN : "NowCoin",
"AEC*" : "EmaratCoin",
"BTF*" : "BitcoinFor",
"GMC*" : "GMC Coin",
ICST : "ICST",
PURK : "Purk",
ROE : "Rover Coin",
DKD : "Dekado",
LYNX : "Lynx",
POSQ : "Poseidon Quark",
"OCTO*" : "OctoBit Coin",
YCE : "MYCE",
OCC : "Original Crypto Coin",
ARO : "Arionum",
BWS : "BitcoinWSpectrum",
BTCC : "Bitcoin Core",
GOLF : "GolfCoin",
MUSE : "Muse",
OCT : "OracleChain",
XCEL : "XcelTrip",
ECH : "EthereCash",
XMN : "Motion",
PLUS1 : "PlusOneCoin",
COI : "Coinnec",
GMCN : "GambleCoin",
TRVC : "Trivecoin",
KRX : "RAVN Korrax ",
"OPP*" : "OPP Open WiFi",
DTEM : "Dystem",
SOUND : "Inmusik",
TRW : "Triwer",
GIC : "Giant",
EPIK : "EPIK Token",
ZMN : "ZMINE",
PNY : "Peony Coin",
SAFE : "SafeCoin",
COU : "Couchain",
BID : "BidCoin",
ATH : "Atheios",
ABS : "Absolute Coin",
"JOY*" : "JOYSO",
VITAE : "Vitae",
"0xDIARY" : "The 0xDiary Token",
"BTCS*" : "Bitcoin Supreme",
TDP : "TrueDeck",
XGS : "GenesisX",
XUEZ : "XUEZ",
BIM : "BitminerCoin",
Dow : "DowCoin",
HEX : "HexCoin",
PYT : "Payther",
DEI : "Deimos",
TPC : "TPCash",
OYS : "Oyster Platform",
"WEB*" : "Webchain",
VIDT : "V-ID",
JEX : "JEX Token",
RYO : "Ryo",
MUSD : "MUSDcoin",
MIC : "Mindexcoin",
URALS : "Urals Coin",
QWC : "Qwertycoin",
BTN : "Bitcoin Nova",
ARE : "ARENON",
DAC : "DACash",
EUNO : "EUNO",
MMO : "MMOCoin",
MVP : "Merculet",
DASC : "DasCoin",
EGT : "Egretia",
"MET*" : "Metronome",
PGT : "Puregold token",
SLT : "SmartLands",
TGAME : "TrueGame",
"SPN*" : "Sapien Network",
ZINC : "ZINC",
KETAN : "Ketan",
INSUR : "InsurChain Coin",
NIX : "NIX",
FIN : "Finom FIN Token",
RPM : "Render Payment",
ITA : "Italocoin",
NOM : "Finom NOM Token",
XSTC : "Safe Trade Coin",
EGCC : "Engine",
FREC : "Freyrchain",
AOA : "Aurora ",
LET : "LinkEye",
MYB : "MyBit",
BNB : "Binance Coin",
OMG : "OmiseGo",
ICX : "ICON Project",
ZRX : "0x",
AE : "Aeternity",
MKR : "Maker",
REP : "Augur",
"BTM*" : "Bytom",
NPXS : "Pundi X",
WTC : "Waltonchain",
BAT : "Basic Attention Token",
GNT : "Golem Network Token",
RHOC : "RChain",
SNT : "Status Network Token",
PPT : "Populous",
DGD : "Digix DAO",
IOST : "IOS token",
HT : "Huobi Token",
AION : "Aion",
LRC : "Loopring",
NAS : "Nebulas",
ELF : "aelf",
FUN : "FunFair",
KNC : "Kyber Network",
DCN : "Dentacoin",
LOOM : "Loom Network",
MCO : "Monaco",
WAX : "Worldwide Asset eXchange",
BNT : "Bancor Network Token",
KIN : "Kin",
BQX : "Ethos",
POWR : "Power Ledger",
NULS : "Nuls",
MANA : "Decentraland",
VERI : "Veritaseum",
"CMT*" : "CyberMiles",
QASH : "Quoine Liquid",
"POLY*" : "Polymath Network",
ENG : "Enigma",
CTXC : "Cortex",
NOAH : "NOAHCOIN",
THETA : "Theta",
TUSD : "True USD",
SUB : "Substratum Network",
BIX : "BiboxCoin",
"XIN*" : "Mixin",
"MTN**" : "Motion",
"PAI*" : "Project Pai",
STORM : "Storm",
FSN : "Fusion",
GTC : "Game",
"MAN*" : "Matrix AI Network",
DRGN : "Dragonchain",
HPB : "High Performance Blockchain",
SALT : "Salt Lending",
CVC : "Civic",
ICN : "Iconomi",
AGI : "SingularityNET",
STORJ : "Storj",
SAN : "Santiment",
RLC : "iEx.ec",
CVT : "CyberVein",
NCASH : "Nucleus Vision",
MEET : "CoinMeet",
BOE : "Bodhi ",
RTE : "Rate3 ",
UBC : "Ubcoin",
HB : "HeartBout",
XET : "Eternal Token",
PCO : "Pecunio",
XPST : "PokerSports",
NBC : "Niobium",
CET : "CoinEx token",
HSC : "HashCoin ",
CAR : "CarBlock ",
REN : "Republic Token",
KEP : "Kepler",
XPAT : "Bitnation Pangea",
SCRL : "Scroll",
LCK : "Luckbox",
MRPH : "Morpheus Network",
GNO : "Gnosis",
R : "Revain",
ELI : "Eligma",
"HOT*" : "Holo",
NEXO : "NEXO",
REQ : "Request Network",
DATA : "Streamr DATAcoin",
ANT : "Aragon",
ENJ : "Enjin Coin",
CND : "Cindicator",
RUFF : "Ruff",
QSP : "Quantstamp",
SNM : "SONM",
KICK : "KickCoin",
AMB : "Ambrosus",
"ABT*" : "ArcBlock",
DENT : "Dent",
"CS*" : "Credits",
AUTO : "Cube",
MTC : "DOCADEMIC",
POE : "Po.et",
"RDN*" : "Raiden Network",
EBC : "EBCoin",
C20 : "Crypto20",
PLR : "Pillar",
BRD : "Bread token",
STQ : "Storiqa Token",
GNX : "Genaro Network",
SPHTX : "SophiaTX",
MFT : "Mainframe",
VEE : "BLOCKv",
MTL : "Metal",
JOINT : "Joint Ventures",
TEL : "Telcoin",
TEN : "Tokenomy",
CONI : "CoinBene",
MBLC : "Mont Blanc",
DIW : "DIWtoken",
EOS : "EOS",
XRP : "XRP",
ATMI : "Atonomi",
"ROCK*" : "RocketCoin ",
BITX : "BitScreener",
CCO : "Ccore",
ETK : "Energi Token",
"SMT**" : "Social Media Market",
FSBT : "Forty Seven Bank",
OLT : "OneLedger",
RMT : "SureRemit",
TIO : "Trade.io",
KEY : "SelfKey",
EDG : "Edgeless",
LEND : "EthLend",
LGO : "Legolas Exchange",
CRPT : "Crypterium",
SOAR : "Soarcoin",
EDO : "Eidoo",
TRAC : "OriginTrail",
"SKB*" : "Sakura Bloom",
QKC : "QuarkChain",
ADX : "AdEx",
HYDRO : "Hydrogen",
"NEC*" : "Ethfinex Nectar Token",
ITC : "IoT Chain",
RKT : "Rock Token",
BCAP : "Blockchain Capital",
"EDR*" : "Endor Protocol Token ",
JNT : "Jibrel Network Token",
INT : "Internet Node Token",
SNTR : "Silent Notary",
COV : "Covesting",
APIS : "APIS",
LST : "Lendroid Support Token",
DREAM : "DreamTeam Token",
EMV : "Ethereum Movie Venture",
MEDX : "Mediblock",
GETX : "Guaranteed Ethurance Token Extra",
BWT : "Bittwatt",
BTRN : "Biotron",
XMX : "XMax",
DNT : "district0x",
SNGLS : "SingularDTV",
AST : "AirSwap",
PAI : "PCHAIN",
TKN : "TokenCard  ",
"DCC*" : "Distributed Credit Chain",
UTK : "Utrust",
DBET : "Decent.bet",
UTT : "United Traders Token",
"CPC*" : "CPChain",
SPANK : "SpankChain",
HOT : "Hydro Protocol",
TRX : "Tronix",
CANDY : "UnicornGo Candy",
APPC : "AppCoins",
UTNP : "Universa Token",
PPP : "PayPie",
INS : "INS Ecosystem",
TOMO : "TomoChain",
WINGS : "Wings DAO",
WPR : "WePower",
NGC : "NagaCoin",
TNT : "Tierion",
YEE : "Yee",
MOD : "Modum",
RNTB : "BitRent",
EXC : "Eximchain",
MSP : "Mothership",
SXDT : "SPECTRE Dividend Token",
DOCK : "Dock.io",
COB : "Cobinhood",
WABI : "WaBi",
ESZ : "EtherSportz",
IQ : "Everipedia",
LUN : "Lunyr",
"PRE*" : "Presearch",
ZCO : "Zebi Coin",
FUEL : "Etherparty",
PST : "Primas",
SPF : "SportyCo",
CDT : "Blox",
AURA : "Aurora",
YOYOW : "Yoyow",
VIBE : "VIBEHub",
TFD : "TE-FOOD",
TAAS : "Token as a Service",
HVN : "Hive Project",
DAT : "Datum",
SENT : "Sentinel",
CPT : "Cryptaur",
CMCT : "Crowd Machine",
CREDO : "Credo",
SNIP : "SnipCoin",
VME : "VeriME",
XDNA : "XDNA",
VITE : "VITE",
U42 : "You42",
SAL : "SalPay",
RNT : "OneRoot Network",
BBO : "Bigbom",
YUP : "Crowdholding",
DAI : "Dai",
NMR : "Numeraire",
SKRP : "Skraps",
HALO : "Halo Platform",
PITCH : "PITCH",
CARD : "Cardstack",
THRT : "ThriveToken",
LIKE : "LikeCoin",
AVH : "Animation Vision Cash",
SCC : "StockChain Coin",
BSTN : "BitStation",
NANJ : "NANJCOIN",
PAXEX : "PAXEX",
SLX : "Slate",
AMO : "Amo Coin",
HYT : "HoryouToken",
STT : "Staramba",
EMN : "Eminent Token ",
DEC : "Darico",
HFT : "Hirefreehands",
GEX : "GreenX",
BETT : "Bettium",
AIC : "AI Crypto",
DIT : "Ditcoin",
ENK : "Enkidu",
MNTS : "Mint",
CTKN : "Curaizon",
PAVO : "Pavocoin",
HAC : "Hackspace Capital",
AZART : "Azart",
RDC : "Ordocoin",
FREE : "FREE coin",
TRIP : "Trippki",
IVY : "IvyKoin",
AOP : "Averopay",
BTM : "BitMark",
INTO : "Influ Token",
SDRN : "Senderon",
AIMS : "HighCastle Token",
TSC : "ThunderStake",
SPLB : "SimpleBank",
CMZ : "CRYPTOMAGZ",
MOIN : "MoinCoin",
ERC20 : "Index ERC20",
BANCA : "BANCA",
"ZSC*" : "ZeroState",
IMV : "ImmVRse",
SMART : "SmartCash",
ILK : "Inlock",
RAC : "RAcoin",
WYS : "Wysker",
LIGER : "Ligercoin",
NLG : "Gulden",
LINK : "ChainLink",
SFT : "SportsFix",
HTML : "HTML Coin",
WORK : "Aworker",
PHT : "Photochain",
SWM : "Swarm Fund",
STX : "Stox",
HMQ : "Humaniq",
EVN : "Envion",
DATX : "DATx",
BMC : "Blackmoon Crypto",
BKX : "BANKEX",
GRID : "Grid+",
"1ST" : "FirstBlood",
PRO : "Propy",
UKG : "UnikoinGold",
MDA : "Moeda",
BCPT : "BlockMason Credit Protocol",
XYO : "XY Oracle",
BBC : "TraDove",
XDCE : "XinFin Coin",
"DNET*" : "DeNet",
FNP : "FlipNpik",
QUA : "Quasa",
SHPT : "Shipit",
FAN : "Fan360",
KBC : "Karatgold coin",
PRL : "Oyster Pearl",
COIN : "Coinvest",
XAP : "Apollon",
BUD : "Buddy",
HMD : "Homelend",
IMGZ : "Imigize",
RSC : "Ronaldinho Soccer Coin",
ZAZA : "ZAZA",
"CCC*" : "Blockshipping",
MLN : "Melon",
ZCN : "0chain",
UUU : "U Network",
ART : "Maecenas",
ZSC : "Zeusshield",
UP : "UpToken",
MRK : "MARK.SPACE",
MOT : "Olympus Labs",
PLBT : "Polybius",
MGO : "MobileGo",
CEEK : "CEEK Smart VR Token",
EVX : "Everex",
UPP : "Sentinel Protocol",
QUN : "QunQun",
DXT : "DataWallet",
HST : "Decision Token",
BZNT : "Bezant",
XRL : "Rialto.AI",
PRG : "Paragon",
UQC : "Uquid Coin",
TIX : "Blocktix",
COSS : "COSS",
"BBN*" : "Banyan Network",
XES : "Proxeus",
STRY : "STRYKZ",
MCV : "MCV Token",
OIO : "Online",
HAV : "Havven",
HPAY : "HadePay",
KAAS : "KAASY.AI",
MHP : "MedicoHealth",
WHEN : "WhenHub",
URB : "Urbit Data",
VET : "Vechain",
CTL : "Citadel",
BOLI : "BolivarCoin",
MONK : "Monkey Project",
DNN : "DNN Token",
UBT : "UniBright",
BMX : "BitMart Coin",
RUP : "Rupee",
GEM : "Gems",
LEV : "Leverj",
ALX : "ALAX",
CSNO : "BitDice",
IPL : "InsurePal",
GET : "Guaranteed Entrance Token",
REX : "Imbrex",
BERRY : "Rentberry",
J8T : "JET8",
DRT : "DomRaider",
HBZ : "Helbiz",
"GEN*" : "DAOstack",
XAUR : "Xaurum",
LATX : "LatiumX",
BEZ : "Bezop",
"MDT*" : "Measurable Data Token ",
COFI : "CoinFi",
EXY : "Experty",
AIR : "AirToken",
HBT : "Hubii Network",
REBL : "REBL",
REAL : "REAL",
DEB : "Debitum Token",
AID : "AidCoin",
EKO : "EchoLink",
RVT : "Rivetz",
CSC : "CasinoCoin",
AVT : "AventCoin",
ATM : "ATMChain",
TFL : "True Flip Lottery",
SS : "Sharder",
POLL : "ClearPoll",
FLIXX : "Flixxo",
IDXM : "IDEX Membership",
CLN : "Colu Local Network",
"BET*" : "DAO.casino",
MYST : "Mysterium",
B2B : "B2BX",
PTOY : "Patientory",
PKT : "Playkey",
LEDU : "Education Ecosystem",
NIM : "Nimiq ",
LYK : "Loyakk Vega",
RUBY : "Rubius",
TIP : "Tip Blockchain",
PERU : "PeruCoin",
ORBS : "Orbis",
OMI : "ECOMI",
CBT : "CommerceBlock Token",
HER : "Hero Node",
TRAK : "TrakInvest",
BDG : "BitDegree",
FLP : "Gameflip",
ALIS : "ALISmedia",
WAB : "WABnetwork",
AEN : "Aenco",
SOLID : "Solidified",
XDT : "Dataeum",
BILL : "TillBilly",
OFCR : "OfficerCoin",
"ATX*" : "Aston",
CCCX : "Clipper Coin Capital",
PROUD : "PROUD Money",
HDAC : "Hdac",
APL : "Apollo Currency",
COT : "CoTrader",
"ETT*" : "Eternal Trusts",
PRLPAY : "PearlPay",
LED : "Terawatt",
NBOX : "Unboxed",
FLEX : "TrustedCars FLEX",
RBDT : "RoBust Defense Token",
ARR : "ARROUND",
DBCCOIN : "Datablockchain",
AIRE : "Tokenaire",
GMA : "Goldchip Mining Asset",
WPT : "Worldopoly",
PSK : "Pool of Stake",
YBT : "YellowBetter",
SKYFT : "SKYFchain",
"CRS*" : "CRYSTALS",
"ARB*" : "ARBITRAGE",
QRL : "Quantum Resistant Ledger",
RAWG : "RAWG",
SPIKE : "Spiking",
MFX : "MFChain",
DYNO : "DYNO",
Pakka : "NextPakk",
SPOT : "Spotcoin",
ENTRY : "ENTRY",
ZEEW : "Zeew",
CHART : "BetOnChart",
IAM : "IAME Identity",
NYN : "NYNJA",
K2G : "Kasko2go",
IMU : "imusify",
QCX : "QuickX Protocol",
WPP : "Green Energy Token",
CDPT : "Creditor Data Platform",
MCB : "MyCryptoBank",
ST : "Scienceroot",
SLN : "Social Lending Network",
WMB : "WatermelonBlock",
BELA : "Bela",
DIP : "Etherisc",
ENQ : "Enecuum",
DTN : "Datareum",
ONT : "Ontology",
ISR : "Insureum",
OSA : "Optimal Shelf Availability Token",
"EMT*" : "Memority",
BGL : "Buglab",
JSE : "JSEcoin",
KVT : "Kinesis Velocity Token ",
ITR : "INTRO",
GLDR : "WAR FIELD",
BMK : "Benchmark",
PLMT : "Pallium",
DGX : "Digix Gold token",
PLU : "Pluton",
WTT : "Giga Watt",
XNK : "Ink Protocol",
HKN : "Hacken",
SWT : "Swarm City Token",
ZAP : "Zap",
"LNC*" : "Linker Coin",
TRST : "TrustCoin",
DRP : "DCORP",
OTN : "Open Trading Network",
PRIX : "Privatix",
SENC : "Sentinel Chain",
IND : "Indorse",
DTH : "Dether",
CAN : "CanYaCoin",
RLX : "Relex",
SCL : "Sociall",
ADB : "Adbank",
ADST : "Adshares",
PBL : "Pebbles",
SENSE : "Sense Token",
HUR : "Hurify",
HDG : "Hedge Token",
BNTY : "Bounty0x",
BEE : "Bee Token",
EVC : "Eventchain",
IFT : "InvestFeed",
TGT : "TargetCoin",
PAL : "PolicyPal Network",
GAT : "GATCOIN",
MTX : "Matryx",
PFR : "PayFair",
SNOV : "Snovio",
EVE : "Devery",
SXUT : "SPECTRE Utility Token",
ASTRO : "Astronaut",
MITX : "Morpheus Infrastructure Token",
"SHP*" : "Sharpe Capital",
LND : "Lendingblock",
INSTAR : "Insights Network",
BLUE : "Ethereum Blue",
PARETO : "Pareto Network Token",
"CAT*" : "BitClave",
HGT : "Hello Gold",
SIG : "Signal",
ARY : "Block Array",
"0XBTC" : "0xBitcoin",
GLA : "Gladius",
ORS : "ORS Group",
KIND : "Kind Ads",
IPSX : "IP Exchange",
VIT : "Vice Industry Token",
ATL : "ATLANT",
RCT : "RealChain",
LOCI : "LociCoin",
BETR : "BetterBetting",
X8X : "X8Currency",
"NIO*" : "Autonio",
ZIPT : "Zippie",
UFR : "Upfiring",
PLAY : "HEROcoin",
FYP : "FlypMe",
NDC : "NeverDie",
CPAY : "CryptoPay",
NAVI : "NaviAddress",
ZXC : "Oxcert",
ETBS : "EthBits",
FTX : "FintruX",
LALA : "LaLa World",
CTR : "Centra",
WISH : "MyWish",
"BON*" : "Bonpay",
TBX : "Tokenbox",
HORSE : "Ethorse ",
FUCK : "Fuck Token",
AUC : "Auctus",
TKA : "Tokia",
ONL : "On.Live",
VOISE : "Voise",
"INV*" : "Invacio",
OPT : "Opus",
TIE : "Ties Network",
CPY : "COPYTRACK",
MFG : "SyncFab",
SHL : "Oyster Shell",
CAT : "BlockCAT",
WRC : "Worldcore",
TEAM : "TeamUP",
BEX : "BEX token",
UBEX : "Ubex",
IDAP : "IDAP",
REDC : "RedCab",
TRN : "Ternion",
USD:  "US Dollar",
CAD:  "Canadian Dollar",
EUR:"Euro",
INR:"Indian Rupee"
}    